// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddWorkspaceToPrivateNetwork implements addWorkspaceToPrivateNetwork operation.
//
// Publishes a workspace in your team's [Private API Network].
//
// POST /network/private
//
// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
func (UnimplementedHandler) AddWorkspaceToPrivateNetwork(ctx context.Context, req *AddWorkspace) (r AddWorkspaceToPrivateNetworkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ApproveDenyAccessRequest implements approveDenyAccessRequest operation.
//
// Approve or deny a team's access request.
//
// POST /teams/{teamId}/access-requests/{requestId}
func (UnimplementedHandler) ApproveDenyAccessRequest(ctx context.Context, req *ApproveDenyAccessRequest, params ApproveDenyAccessRequestParams) (r ApproveDenyAccessRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AsyncMergePullCollectionFork implements asyncMergePullCollectionFork operation.
//
// [Merges] a forked (source) collection and its parent (destination) collection asynchronously. To
// pull changes into a fork, pass the forked collection's ID as the `destination` value and the parent
// collection ID as the `source` value.
//
// PUT /collection-merges
//
// [Merges]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/#merge-changes-from-a-fork
func (UnimplementedHandler) AsyncMergePullCollectionFork(ctx context.Context, req *MergePullCollectionChanges) (r AsyncMergePullCollectionForkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AsyncMergePullCollectionTaskStatus implements asyncMergePullCollectionTaskStatus operation.
//
// Gets the status of a collection's merge or a pull changes task.
//
// GET /collection-merges-tasks/{taskId}
func (UnimplementedHandler) AsyncMergePullCollectionTaskStatus(ctx context.Context, params AsyncMergePullCollectionTaskStatusParams) (r AsyncMergePullCollectionTaskStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAccessRequest implements createAccessRequest operation.
//
// Creates an access request for a team. Access requests include actions such as request to join a
// team, upgrading a user's role, adding members, and requesting team role access to another team.
//
// POST /teams/{teamId}/access-requests
func (UnimplementedHandler) CreateAccessRequest(ctx context.Context, req *CreateAccessRequest, params CreateAccessRequestParams) (r CreateAccessRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollection implements createCollection operation.
//
// Creates a collection using the [Postman Collection v2.1.0 schema format].
//
// POST /collections
//
// [Postman Collection v2.1.0 schema format]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) CreateCollection(ctx context.Context, req *CreateCollection, params CreateCollectionParams) (r CreateCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollectionComment implements createCollectionComment operation.
//
// Creates a comment on a collection. To create a reply on an existing comment, include the `threadId`
// property in the request body.
//
// POST /collections/{collectionId}/comments
func (UnimplementedHandler) CreateCollectionComment(ctx context.Context, req *CommentCreate, params CreateCollectionCommentParams) (r CreateCollectionCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollectionFolder implements createCollectionFolder operation.
//
// Creates a folder in a collection. For a complete list of properties, refer to the Folder entry in
// the [Postman Collection Format documentation].
//
// POST /collections/{collectionId}/folders
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) CreateCollectionFolder(ctx context.Context, req *CreateFolder, params CreateCollectionFolderParams) (r CreateCollectionFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollectionFork implements createCollectionFork operation.
//
// Creates a [fork] from an existing collection into a workspace.
//
// POST /collections/fork/{collectionId}
//
// [fork]: https://learning.postman.com/docs/collaborating-in-postman/version-control/#creating-a-fork
func (UnimplementedHandler) CreateCollectionFork(ctx context.Context, req *CreateCollectionFork, params CreateCollectionForkParams) (r CreateCollectionForkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollectionPullRequest implements createCollectionPullRequest operation.
//
// Creates a pull request for a forked collection into its parent collection.
//
// POST /collections/{collectionId}/pull-requests
func (UnimplementedHandler) CreateCollectionPullRequest(ctx context.Context, req *CreatePullRequest, params CreateCollectionPullRequestParams) (r CreateCollectionPullRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollectionRequest implements createCollectionRequest operation.
//
// Creates a request in a collection. For a complete list of properties, refer to the Request entry in
// the [Postman Collection Format documentation].
//
// POST /collections/{collectionId}/requests
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) CreateCollectionRequest(ctx context.Context, req *CreateRequest, params CreateCollectionRequestParams) (r CreateCollectionRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCollectionResponse implements createCollectionResponse operation.
//
// Creates a request response in a collection. For a complete list of request body properties, refer to
// the Response entry in the [Postman Collection Format documentation].
//
// POST /collections/{collectionId}/responses
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) CreateCollectionResponse(ctx context.Context, req *CreateCollectionResponseRequest, params CreateCollectionResponseParams) (r CreateCollectionResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateComponent implements createComponent operation.
//
// Creates a new component. The component is created in an active state with an initial draft. Use the
// POST `/components/{componentId}/versions` endpoint to publish a version.
//
// POST /components
func (UnimplementedHandler) CreateComponent(ctx context.Context, req *CreateComponent) (r CreateComponentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateComponentVersion implements createComponentVersion operation.
//
// Publishes a new version of a component from the current draft.
//
// POST /components/{componentId}/versions
func (UnimplementedHandler) CreateComponentVersion(ctx context.Context, req *CreateComponentVersion, params CreateComponentVersionParams) (r CreateComponentVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEnvironment implements createEnvironment operation.
//
// Creates an environment.
//
// POST /environments
func (UnimplementedHandler) CreateEnvironment(ctx context.Context, req *CreateEnvironment, params CreateEnvironmentParams) (r CreateEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFolderComment implements createFolderComment operation.
//
// Creates a comment on a folder. To create a reply on an existing comment, include the `threadId`
// property in the request body.
//
// POST /collections/{collectionId}/folders/{folderId}/comments
func (UnimplementedHandler) CreateFolderComment(ctx context.Context, req *CommentCreate, params CreateFolderCommentParams) (r CreateFolderCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMock implements createMock operation.
//
// Creates a mock server in a collection.
//
// POST /mocks
func (UnimplementedHandler) CreateMock(ctx context.Context, req *CreateMock, params CreateMockParams) (r CreateMockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMockServerResponse implements createMockServerResponse operation.
//
// Creates a server response. Server responses let you simulate 5xx server-level responses, such as 500
// or 503.
//
// POST /mocks/{mockId}/server-responses
func (UnimplementedHandler) CreateMockServerResponse(ctx context.Context, req *CreateMockServerResponse, params CreateMockServerResponseParams) (r CreateMockServerResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMonitor implements createMonitor operation.
//
// Creates a monitor.
//
// POST /monitors
func (UnimplementedHandler) CreateMonitor(ctx context.Context, req *CreateMonitor, params CreateMonitorParams) (r CreateMonitorRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRequestComment implements createRequestComment operation.
//
// Creates a comment on a request. To create a reply on an existing comment, include the `threadId`
// property in the request body.
//
// POST /collections/{collectionId}/requests/{requestId}/comments
func (UnimplementedHandler) CreateRequestComment(ctx context.Context, req *CommentCreate, params CreateRequestCommentParams) (r CreateRequestCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateResponseComment implements createResponseComment operation.
//
// Creates a comment on a response. To create a reply on an existing comment, include the `threadId`
// property in the request body.
//
// POST /collections/{collectionId}/responses/{responseId}/comments
func (UnimplementedHandler) CreateResponseComment(ctx context.Context, req *CommentCreate, params CreateResponseCommentParams) (r CreateResponseCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSdk implements createSdk operation.
//
// Creates an asynchronous generation job for a single SDK (in one language) from a collection or
// specification.
//
// POST /sdks
func (UnimplementedHandler) CreateSdk(ctx context.Context, req *CreateSdk) (r CreateSdkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSdkGitConnection implements createSdkGitConnection operation.
//
// Connects a Postman source element (collection or specification) to a Git repository for one SDK
// language. This creates a new connection in the`active` state.
//
// POST /sdk-git-connections
func (UnimplementedHandler) CreateSdkGitConnection(ctx context.Context, req *CreateSdkGitConnection) (r CreateSdkGitConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpec implements createSpec operation.
//
// Creates an API specification in Postman's [Spec Hub]. Specifications can be single or multi-file.
//
// POST /specs
//
// [Spec Hub]: https://learning.postman.com/docs/design-apis/specifications/overview/
func (UnimplementedHandler) CreateSpec(ctx context.Context, req *CreateSpec, params CreateSpecParams) (r CreateSpecRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpecFile implements createSpecFile operation.
//
// Creates a file for an OpenAPI or a protobuf 2 or 3 specification.
//
// POST /specs/{specId}/files
func (UnimplementedHandler) CreateSpecFile(ctx context.Context, req *CreateSpecFile, params CreateSpecFileParams) (r CreateSpecFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSpecVersionTag implements createSpecVersionTag operation.
//
// Creates a version tag for a specification. Version tags are snapshots of a specification at a point
// in time that let you to track changes to your specifications over time.
//
// POST /specs/{specId}/version-tags
func (UnimplementedHandler) CreateSpecVersionTag(ctx context.Context, req *CreateSpecVersionTag, params CreateSpecVersionTagParams) (r CreateSpecVersionTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTeam implements createTeam operation.
//
// [Creates] a Postman team in your organization.
//
// POST /teams
//
// [Creates]: https://learning.postman.com/docs/administration/managing-your-team/create-teams/
func (UnimplementedHandler) CreateTeam(ctx context.Context, req *CreateTeam) (r CreateTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWebhook implements createWebhook operation.
//
// Creates a webhook that triggers a collection with a custom payload. You can get the webhook's URL
// from the `webhookUrl` property in the endpoint's response.
//
// POST /webhooks
func (UnimplementedHandler) CreateWebhook(ctx context.Context, req *CreateWebhook, params CreateWebhookParams) (r CreateWebhookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkspace implements createWorkspace operation.
//
// Creates a new [workspace].
//
// POST /workspaces
//
// [workspace]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/
func (UnimplementedHandler) CreateWorkspace(ctx context.Context, req *CreateWorkspace) (r CreateWorkspaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkspaceUpdate implements createWorkspaceUpdate operation.
//
// Creates a [workspace update] in the given workspace. Workspace updates keep workspace watchers
// informed about changes, such as new features, bug fixes, breaking changes, and announcements.
//
// POST /workspaces/{workspaceId}/updates
//
// [workspace update]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/internal-workspaces/workspace-updates
func (UnimplementedHandler) CreateWorkspaceUpdate(ctx context.Context, req *CreateWorkspaceUpdate, params CreateWorkspaceUpdateParams) (r CreateWorkspaceUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollection implements deleteCollection operation.
//
// Deletes a collection.
//
// DELETE /collections/{collectionId}
func (UnimplementedHandler) DeleteCollection(ctx context.Context, params DeleteCollectionParams) (r DeleteCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollectionAccessKey implements deleteCollectionAccessKey operation.
//
// Deletes a collection access key. To get a collection access key's ID, use the GET
// `/collection-access-key` endpoint.
//
// DELETE /collection-access-keys/{keyId}
func (UnimplementedHandler) DeleteCollectionAccessKey(ctx context.Context, params DeleteCollectionAccessKeyParams) (r DeleteCollectionAccessKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollectionComment implements deleteCollectionComment operation.
//
// Deletes a comment from a collection. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /collections/{collectionId}/comments/{commentId}
func (UnimplementedHandler) DeleteCollectionComment(ctx context.Context, params DeleteCollectionCommentParams) (r DeleteCollectionCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollectionFolder implements deleteCollectionFolder operation.
//
// Deletes a folder in a collection.
//
// DELETE /collections/{collectionId}/folders/{folderId}
func (UnimplementedHandler) DeleteCollectionFolder(ctx context.Context, params DeleteCollectionFolderParams) (r DeleteCollectionFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollectionRequest implements deleteCollectionRequest operation.
//
// Deletes a request in a collection.
//
// DELETE /collections/{collectionId}/requests/{requestId}
func (UnimplementedHandler) DeleteCollectionRequest(ctx context.Context, params DeleteCollectionRequestParams) (r DeleteCollectionRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCollectionResponse implements deleteCollectionResponse operation.
//
// Deletes a response in a collection.
//
// DELETE /collections/{collectionId}/responses/{responseId}
func (UnimplementedHandler) DeleteCollectionResponse(ctx context.Context, params DeleteCollectionResponseParams) (r DeleteCollectionResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironment implements deleteEnvironment operation.
//
// Deletes an environment.
//
// DELETE /environments/{environmentId}
func (UnimplementedHandler) DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (r DeleteEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFolderComment implements deleteFolderComment operation.
//
// Deletes a comment from a folder. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /collections/{collectionId}/folders/{folderId}/comments/{commentId}
func (UnimplementedHandler) DeleteFolderComment(ctx context.Context, params DeleteFolderCommentParams) (r DeleteFolderCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMock implements deleteMock operation.
//
// Deletes a mock server.
//
// DELETE /mocks/{mockId}
func (UnimplementedHandler) DeleteMock(ctx context.Context, params DeleteMockParams) (r DeleteMockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMockServerResponse implements deleteMockServerResponse operation.
//
// Deletes a mock server's server response.
//
// DELETE /mocks/{mockId}/server-responses/{serverResponseId}
func (UnimplementedHandler) DeleteMockServerResponse(ctx context.Context, params DeleteMockServerResponseParams) (r DeleteMockServerResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMonitor implements deleteMonitor operation.
//
// Deletes a monitor.
//
// DELETE /monitors/{monitorId}
func (UnimplementedHandler) DeleteMonitor(ctx context.Context, params DeleteMonitorParams) (r DeleteMonitorRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRequestComment implements deleteRequestComment operation.
//
// Deletes a comment from a request. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /collections/{collectionId}/requests/{requestId}/comments/{commentId}
func (UnimplementedHandler) DeleteRequestComment(ctx context.Context, params DeleteRequestCommentParams) (r DeleteRequestCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteResponseComment implements deleteResponseComment operation.
//
// Deletes a comment from a response. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /collections/{collectionId}/responses/{responseId}/comments/{commentId}
func (UnimplementedHandler) DeleteResponseComment(ctx context.Context, params DeleteResponseCommentParams) (r DeleteResponseCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSdk implements deleteSdk operation.
//
// Deletes an SDK record and its stored archive. On success, this returns a `204 No Content` response.
//
// DELETE /sdks/{sdkId}
func (UnimplementedHandler) DeleteSdk(ctx context.Context, params DeleteSdkParams) (r DeleteSdkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSpec implements deleteSpec operation.
//
// Deletes an API specification. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /specs/{specId}
func (UnimplementedHandler) DeleteSpec(ctx context.Context, params DeleteSpecParams) (r DeleteSpecRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSpecFile implements deleteSpecFile operation.
//
// Deletes a file in an API specification. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /specs/{specId}/files/{filePath}
func (UnimplementedHandler) DeleteSpecFile(ctx context.Context, params DeleteSpecFileParams) (r DeleteSpecFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorkspace implements deleteWorkspace operation.
//
// Deletes an existing workspace.
//
// DELETE /workspaces/{workspaceId}
func (UnimplementedHandler) DeleteWorkspace(ctx context.Context, params DeleteWorkspaceParams) (r DeleteWorkspaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorkspaceUpdate implements deleteWorkspaceUpdate operation.
//
// Deletes a workspace update. On success, this returns an HTTP `204 No Content` response.
//
// DELETE /workspaces/{workspaceId}/updates/{updateId}
func (UnimplementedHandler) DeleteWorkspaceUpdate(ctx context.Context, params DeleteWorkspaceUpdateParams) (r DeleteWorkspaceUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DetectedSecretsQueries implements detectedSecretsQueries operation.
//
// Returns all secrets detected by Postman's [Secret Scanner], grouped by workspace or resource. If you
// pass an empty request body, this endpoint returns all results.
//
// POST /detected-secrets-queries
//
// [Secret Scanner]: https://learning.postman.com/docs/administration/secret-scanner/
func (UnimplementedHandler) DetectedSecretsQueries(ctx context.Context, req *DetectedSecretsQueryRequest, params DetectedSecretsQueriesParams) (r DetectedSecretsQueriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DuplicateCollection implements duplicateCollection operation.
//
// Creates a duplicate of the given collection in another workspace.
//
// POST /collections/{collectionId}/duplicates
func (UnimplementedHandler) DuplicateCollection(ctx context.Context, req *DuplicateCollection, params DuplicateCollectionParams) (r DuplicateCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ForkEnvironment implements forkEnvironment operation.
//
// Creates a [fork] of an existing environment.
//
// POST /environments/{environmentId}/forks
//
// [fork]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/
func (UnimplementedHandler) ForkEnvironment(ctx context.Context, req *ForkEnvironment, params ForkEnvironmentParams) (r ForkEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateCollection implements generateCollection operation.
//
// Creates a collection from the given OpenAPI 2.0, 3.0, or 3.1 specification or Smithy specification.
// The response contains a polling link to the task status.
//
// POST /specs/{specId}/generations/{elementType}
func (UnimplementedHandler) GenerateCollection(ctx context.Context, req *GenerateCollection, params GenerateCollectionParams) (r GenerateCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateOauthToken implements generateOauthToken operation.
//
// Generates an OAuth 2.0 access token for a client application using the `client_credentials` grant
// type. Use this endpoint with backend services or bots to authenticate and authorize API requests
// without user interaction.
//
// POST /oauth2/token
func (UnimplementedHandler) GenerateOauthToken(ctx context.Context, req *GenerateOauthToken) (r GenerateOauthTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateServiceAccountToken implements generateServiceAccountToken operation.
//
// Exchanges a service account API key for a short-lived access token. On success, the response
// contains an access token that can be used to authenticate downstream service-to-service requests on
// behalf of the service account. The token is a JWT that encodes the service account's identity and
// permissions, and is valid for 15 minutes.
//
// POST /service-account-tokens
func (UnimplementedHandler) GenerateServiceAccountToken(ctx context.Context) (r GenerateServiceAccountTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateSpecFromCollection implements generateSpecFromCollection operation.
//
// Generates an OpenAPI 2.0, 3.0, or 3.1 specification for the given collection. The response contains
// a polling link to the task status.
//
// POST /collections/{collectionUid}/generations/{elementType}
func (UnimplementedHandler) GenerateSpecFromCollection(ctx context.Context, req *GenerateSpecFromCollection, params GenerateSpecFromCollectionParams) (r GenerateSpecFromCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateTool implements generateTool operation.
//
// This endpoint is deprecated.
//
// POST /postbot/generations/tool
func (UnimplementedHandler) GenerateTool(ctx context.Context, req *GenerateTool) (r GenerateToolRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccountInvoices implements getAccountInvoices operation.
//
// Gets all invoices for a Postman billing account filtered by the status of the invoice.
//
// GET /accounts/{accountId}/invoices
func (UnimplementedHandler) GetAccountInvoices(ctx context.Context, params GetAccountInvoicesParams) (r GetAccountInvoicesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAccounts implements getAccounts operation.
//
// Gets Postman billing account details for the given team.
//
// GET /accounts
func (UnimplementedHandler) GetAccounts(ctx context.Context) (r GetAccountsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllComponents implements getAllComponents operation.
//
// Gets a list of all components in the team's component library.
//
// GET /components
func (UnimplementedHandler) GetAllComponents(ctx context.Context, params GetAllComponentsParams) (r GetAllComponentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllSpecs implements getAllSpecs operation.
//
// Gets all API specifications in a workspace.
//
// GET /specs
func (UnimplementedHandler) GetAllSpecs(ctx context.Context, params GetAllSpecsParams) (r GetAllSpecsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllWorkspaceRoles implements getAllWorkspaceRoles operation.
//
// Gets information about all roles in a workspace, based on the team's [plan].
//
// GET /workspaces-roles
//
// [plan]: https://www.postman.com/pricing/
func (UnimplementedHandler) GetAllWorkspaceRoles(ctx context.Context) (r GetAllWorkspaceRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAnalyticsData implements getAnalyticsData operation.
//
// Gets analytics data based on the specified resource, metrics, and given filters for team, internal,
// and public workspaces, as well as Partner Workspaces.
//
// GET /analytics
func (UnimplementedHandler) GetAnalyticsData(ctx context.Context, params GetAnalyticsDataParams) (r GetAnalyticsDataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAnalyticsMetadata implements getAnalyticsMetadata operation.
//
// Returns a catalog of analytics resources and their corresponding metrics for use with the GET
// /analytics endpoint. These metrics provide insights on API usage, success, workspace, and team
// trends in Postman.
//
// GET /analytics-metadata
func (UnimplementedHandler) GetAnalyticsMetadata(ctx context.Context, params GetAnalyticsMetadataParams) (r GetAnalyticsMetadataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAsyncSpecTaskStatus implements getAsyncSpecTaskStatus operation.
//
// Gets the status of an asynchronous API specification creation task.
//
// GET /{elementType}/{elementId}/tasks/{taskId}
func (UnimplementedHandler) GetAsyncSpecTaskStatus(ctx context.Context, params GetAsyncSpecTaskStatusParams) (r GetAsyncSpecTaskStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuditLogEventActions implements getAuditLogEventActions operation.
//
// Gets a complete list of all available audit log event actions.
//
// GET /audit-actions
func (UnimplementedHandler) GetAuditLogEventActions(ctx context.Context) (r GetAuditLogEventActionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuditLogs implements getAuditLogs operation.
//
// Gets a list of your team's generated audit events. For a complete list of all audit events, see
// [Audit logs].
//
// GET /audit/logs
//
// [Audit logs]: https://learning.postman.com/docs/administration/audit-logs/
func (UnimplementedHandler) GetAuditLogs(ctx context.Context, params GetAuditLogsParams) (r GetAuditLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuthenticatedUser implements getAuthenticatedUser operation.
//
// Gets information about the authenticated user.
//
// GET /me
func (UnimplementedHandler) GetAuthenticatedUser(ctx context.Context) (r GetAuthenticatedUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollection implements getCollection operation.
//
// Gets information about a collection. For a complete list of this endpoint's possible values, refer
// to the [Postman Collection Format documentation].
//
// GET /collections/{collectionId}
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) GetCollection(ctx context.Context, params GetCollectionParams) (r GetCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionAccessKeys implements getCollectionAccessKeys operation.
//
// Gets the authenticated user's personal and team [collection access keys].
//
// GET /collection-access-keys
//
// [collection access keys]: https://learning.postman.com/docs/developer/postman-api/authentication/#generate-a-collection-access-key
func (UnimplementedHandler) GetCollectionAccessKeys(ctx context.Context, params GetCollectionAccessKeysParams) (r GetCollectionAccessKeysRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionComments implements getCollectionComments operation.
//
// Gets all comments left by users in a collection.
//
// GET /collections/{collectionId}/comments
func (UnimplementedHandler) GetCollectionComments(ctx context.Context, params GetCollectionCommentsParams) (r GetCollectionCommentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionFolder implements getCollectionFolder operation.
//
// Gets information about a folder in a collection.
//
// GET /collections/{collectionId}/folders/{folderId}
func (UnimplementedHandler) GetCollectionFolder(ctx context.Context, params GetCollectionFolderParams) (r GetCollectionFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionForks implements getCollectionForks operation.
//
// Gets a collection's forked collections. The response returns data for each fork, such as the fork's
// ID, the user who forked it, and the fork's creation date.
//
// GET /collections/{collectionId}/forks
func (UnimplementedHandler) GetCollectionForks(ctx context.Context, params GetCollectionForksParams) (r GetCollectionForksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionPullRequests implements getCollectionPullRequests operation.
//
// Gets information about a collection's pull requests, such as the source and destination IDs, status
// of the pull requests, and a URL link to the pull requests.
//
// GET /collections/{collectionId}/pull-requests
func (UnimplementedHandler) GetCollectionPullRequests(ctx context.Context, params GetCollectionPullRequestsParams) (r GetCollectionPullRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionRequest implements getCollectionRequest operation.
//
// Gets information about a request in a collection.
//
// GET /collections/{collectionId}/requests/{requestId}
func (UnimplementedHandler) GetCollectionRequest(ctx context.Context, params GetCollectionRequestParams) (r GetCollectionRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionResponse implements getCollectionResponse operation.
//
// Gets information about a response in a collection.
//
// GET /collections/{collectionId}/responses/{responseId}
func (UnimplementedHandler) GetCollectionResponse(ctx context.Context, params GetCollectionResponseParams) (r GetCollectionResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionRoles implements getCollectionRoles operation.
//
// Gets information about all roles in a collection. The response returns the IDs of all users, teams,
// and groups with access to view or edit the collection.
//
// GET /collections/{collectionId}/roles
func (UnimplementedHandler) GetCollectionRoles(ctx context.Context, params GetCollectionRolesParams) (r GetCollectionRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionTags implements getCollectionTags operation.
//
// Gets all the tags associated with a collection.
//
// GET /collections/{collectionId}/tags
func (UnimplementedHandler) GetCollectionTags(ctx context.Context, params GetCollectionTagsParams) (r GetCollectionTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionUpdatesTasks implements getCollectionUpdatesTasks operation.
//
// Gets the status of an asynchronous collection update task.
//
// GET /collection-updates-tasks/{taskId}
func (UnimplementedHandler) GetCollectionUpdatesTasks(ctx context.Context, params GetCollectionUpdatesTasksParams) (r GetCollectionUpdatesTasksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollections implements getCollections operation.
//
// Gets all of your [collections]. The response includes all of your subscribed collections.
//
// GET /collections
//
// [collections]: https://www.postman.com/docs/collections
func (UnimplementedHandler) GetCollections(ctx context.Context, params GetCollectionsParams) (r GetCollectionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCollectionsForkedByUser implements getCollectionsForkedByUser operation.
//
// Gets a list of all the authenticated user's forked collections.
//
// GET /collections/collection-forks
func (UnimplementedHandler) GetCollectionsForkedByUser(ctx context.Context, params GetCollectionsForkedByUserParams) (r GetCollectionsForkedByUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetComponent implements getComponent operation.
//
// Gets information about a component. Use the `include` and `expand` query parameters to return
// additional information, such as `hasVersions` and the latest published version.
//
// GET /components/{componentId}
func (UnimplementedHandler) GetComponent(ctx context.Context, params GetComponentParams) (r GetComponentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetComponentDraft implements getComponentDraft operation.
//
// Gets information about the current working draft of a component, including its content and format.
// Drafts represent the latest unpublished edits of a component, which may be different from the most
// recently published version.
//
// GET /components/{componentId}/drafts
func (UnimplementedHandler) GetComponentDraft(ctx context.Context, params GetComponentDraftParams) (r GetComponentDraftRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetComponentVersion implements getComponentVersion operation.
//
// Gets a published version of a component.
//
// GET /components/{componentId}/versions/{versionId}
func (UnimplementedHandler) GetComponentVersion(ctx context.Context, params GetComponentVersionParams) (r GetComponentVersionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetComponentVersions implements getComponentVersions operation.
//
// Gets a list of a component's published versions.
//
// GET /components/{componentId}/versions
func (UnimplementedHandler) GetComponentVersions(ctx context.Context, params GetComponentVersionsParams) (r GetComponentVersionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDetectedSecretsLocations implements getDetectedSecretsLocations operation.
//
// Gets the locations of secrets detected by Postman's [Secret Scanner].
//
// GET /detected-secrets/{secretId}/locations
//
// [Secret Scanner]: https://learning.postman.com/docs/administration/secret-scanner/
func (UnimplementedHandler) GetDetectedSecretsLocations(ctx context.Context, params GetDetectedSecretsLocationsParams) (r GetDetectedSecretsLocationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDuplicateCollectionTaskStatus implements getDuplicateCollectionTaskStatus operation.
//
// Gets the status of a collection duplication task.
//
// GET /collection-duplicate-tasks/{taskId}
func (UnimplementedHandler) GetDuplicateCollectionTaskStatus(ctx context.Context, params GetDuplicateCollectionTaskStatusParams) (r GetDuplicateCollectionTaskStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironment implements getEnvironment operation.
//
// Gets information about an environment.
//
// GET /environments/{environmentId}
func (UnimplementedHandler) GetEnvironment(ctx context.Context, params GetEnvironmentParams) (r GetEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironmentForks implements getEnvironmentForks operation.
//
// Gets all of an environment's forked environments.
//
// GET /environments/{environmentId}/forks
func (UnimplementedHandler) GetEnvironmentForks(ctx context.Context, params GetEnvironmentForksParams) (r GetEnvironmentForksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironments implements getEnvironments operation.
//
// Gets information about all of your [environments].
//
// GET /environments
//
// [environments]: https://learning.postman.com/docs/sending-requests/managing-environments/
func (UnimplementedHandler) GetEnvironments(ctx context.Context, params GetEnvironmentsParams) (r GetEnvironmentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFolderComments implements getFolderComments operation.
//
// Gets all comments left by users in a folder.
//
// GET /collections/{collectionId}/folders/{folderId}/comments
func (UnimplementedHandler) GetFolderComments(ctx context.Context, params GetFolderCommentsParams) (r GetFolderCommentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGeneratedCollectionSpecs implements getGeneratedCollectionSpecs operation.
//
// Migrates an API Builder definition to a [Spec Hub] specification. You can migrate the definition to
// an existing workspace, or create a new workspace to migrate the definition into. On success, this
// returns an HTTP `202 Created` response. You can use the GET `/apis/{apiId}/spec-migrations` endpoint
// to check the migration status.
//
// GET /collections/{collectionUid}/generations/{elementType}
//
// [Spec Hub]: https://learning.postman.com/docs/design-apis/specifications/overview
func (UnimplementedHandler) GetGeneratedCollectionSpecs(ctx context.Context, params GetGeneratedCollectionSpecsParams) (r GetGeneratedCollectionSpecsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroup implements getGroup operation.
//
// Gets information about a Postman [user group].
//
// GET /groups/{groupId}
//
// [user group]: https://learning.postman.com/docs/collaborating-in-postman/user-groups/
func (UnimplementedHandler) GetGroup(ctx context.Context, params GetGroupParams) (r GetGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGroups implements getGroups operation.
//
// Gets all of a team's Postman [groups].
//
// GET /groups
//
// [groups]: https://learning.postman.com/docs/collaborating-in-postman/user-groups/
func (UnimplementedHandler) GetGroups(ctx context.Context) (r GetGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMock implements getMock operation.
//
// Gets information about a mock server.
//
// GET /mocks/{mockId}
func (UnimplementedHandler) GetMock(ctx context.Context, params GetMockParams) (r GetMockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMockCallLogs implements getMockCallLogs operation.
//
// Gets a mock server's call logs. You can get a maximum of 6.5MB of call logs or a total of 100 call
// logs, whichever limit is met first in one API call.
//
// GET /mocks/{mockId}/call-logs
func (UnimplementedHandler) GetMockCallLogs(ctx context.Context, params GetMockCallLogsParams) (r GetMockCallLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMockServerResponse implements getMockServerResponse operation.
//
// Gets information about a server response.
//
// GET /mocks/{mockId}/server-responses/{serverResponseId}
func (UnimplementedHandler) GetMockServerResponse(ctx context.Context, params GetMockServerResponseParams) (r GetMockServerResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMockServerResponses implements getMockServerResponses operation.
//
// Gets all of a mock server's server responses.
//
// GET /mocks/{mockId}/server-responses
func (UnimplementedHandler) GetMockServerResponses(ctx context.Context, params GetMockServerResponsesParams) (r GetMockServerResponsesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMocks implements getMocks operation.
//
// Gets all active mock servers. By default, this endpoint returns only mock servers you created across
// all workspaces.
//
// GET /mocks
func (UnimplementedHandler) GetMocks(ctx context.Context, params GetMocksParams) (r GetMocksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitor implements getMonitor operation.
//
// Gets information about a monitor.
//
// GET /monitors/{monitorId}
func (UnimplementedHandler) GetMonitor(ctx context.Context, params GetMonitorParams) (r GetMonitorRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMonitors implements getMonitors operation.
//
// Gets all monitors.
//
// GET /monitors
func (UnimplementedHandler) GetMonitors(ctx context.Context, params GetMonitorsParams) (r GetMonitorsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPullRequest implements getPullRequest operation.
//
// Gets information about a pull request, such as the source and destination details, who reviewed the
// pull request, the merge's current status, and whether the element is accessible.
//
// GET /pull-requests/{pullRequestId}
func (UnimplementedHandler) GetPullRequest(ctx context.Context, params GetPullRequestParams) (r GetPullRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRequestComments implements getRequestComments operation.
//
// Gets all comments left by users in a request.
//
// GET /collections/{collectionId}/requests/{requestId}/comments
func (UnimplementedHandler) GetRequestComments(ctx context.Context, params GetRequestCommentsParams) (r GetRequestCommentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetResponseComments implements getResponseComments operation.
//
// Gets all comments left by users in a response.
//
// GET /collections/{collectionId}/responses/{responseId}/comments
func (UnimplementedHandler) GetResponseComments(ctx context.Context, params GetResponseCommentsParams) (r GetResponseCommentsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRunnerInstances implements getRunnerInstances operation.
//
// Gets all instances of the runner polling Postman for upcoming monitor runs. Instances are runner
// executions that share the same runner ID and key.
//
// GET /runners/{runnerId}/instances
func (UnimplementedHandler) GetRunnerInstances(ctx context.Context, params GetRunnerInstancesParams) (r GetRunnerInstancesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRunnerMetrics implements getRunnerMetrics operation.
//
// Gets the Postman server-side metrics for a runner instance. Metrics include information such as
// monitor run queues and last polling date.
//
// GET /runners/{runnerId}/metrics
func (UnimplementedHandler) GetRunnerMetrics(ctx context.Context, params GetRunnerMetricsParams) (r GetRunnerMetricsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSdk implements getSdk operation.
//
// Returns information about the SDK, including the current build job status.
//
// GET /sdks/{sdkId}
func (UnimplementedHandler) GetSdk(ctx context.Context, params GetSdkParams) (r GetSdkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSdkDownloadUrl implements getSdkDownloadUrl operation.
//
// Gets a short-lived signed URL for the generated SDK archive (zip). The generated URL is created on
// demand and expires within a few minutes.
//
// GET /sdks/{sdkId}/downloads
func (UnimplementedHandler) GetSdkDownloadUrl(ctx context.Context, params GetSdkDownloadUrlParams) (r GetSdkDownloadUrlRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSdkGitConnection implements getSdkGitConnection operation.
//
// Gets information about an SDK's Git connection. The response includes the SDK currently sent to the
// targetBranch and the most recent SDK-update pull request.
//
// GET /sdk-git-connections/{sdkGitConnectionId}
func (UnimplementedHandler) GetSdkGitConnection(ctx context.Context, params GetSdkGitConnectionParams) (r GetSdkGitConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSdkGitConnectionPullRequests implements getSdkGitConnectionPullRequests operation.
//
// Lists all SDK update pull requests for the Git connection, in order of newest first by its
// `updatedAt` property.
//
// GET /sdk-git-connections/{sdkGitConnectionId}/pull-requests
func (UnimplementedHandler) GetSdkGitConnectionPullRequests(ctx context.Context, params GetSdkGitConnectionPullRequestsParams) (r GetSdkGitConnectionPullRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSdkGitConnections implements getSdkGitConnections operation.
//
// Gets all Git repository connections the authenticated user has access to in the given workspace.
// Each connection links one Postman Collection or specification and one SDK language to a target Git
// repository.
//
// GET /sdk-git-connections
func (UnimplementedHandler) GetSdkGitConnections(ctx context.Context, params GetSdkGitConnectionsParams) (r GetSdkGitConnectionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSdks implements getSdks operation.
//
// Lists all SDKs the authenticated user has access to.
//
// GET /sdks
func (UnimplementedHandler) GetSdks(ctx context.Context, params GetSdksParams) (r GetSdksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSecretTypes implements getSecretTypes operation.
//
// Gets the metadata of the secret types supported by Postman's [Secret Scanner]. You can use a secret
// type's ID in the response to query data with the POST `/detected-secrets/{secretId}` endpoint.
//
// GET /secret-types
//
// [Secret Scanner]: https://learning.postman.com/docs/administration/secret-scanner/
func (UnimplementedHandler) GetSecretTypes(ctx context.Context) (r GetSecretTypesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSourceCollectionStatus implements getSourceCollectionStatus operation.
//
// Checks whether there is a change between the forked collection and its parent (source) collection.
//
// GET /collections/{collectionId}/source-status
func (UnimplementedHandler) GetSourceCollectionStatus(ctx context.Context, params GetSourceCollectionStatusParams) (r GetSourceCollectionStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpec implements getSpec operation.
//
// Gets information about an API specification.
//
// GET /specs/{specId}
func (UnimplementedHandler) GetSpec(ctx context.Context, params GetSpecParams) (r GetSpecRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpecCollections implements getSpecCollections operation.
//
// Gets all of an API specification's generated collections.
//
// GET /specs/{specId}/generations/{elementType}
func (UnimplementedHandler) GetSpecCollections(ctx context.Context, params GetSpecCollectionsParams) (r GetSpecCollectionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpecDefinition implements getSpecDefinition operation.
//
// Gets the complete contents of an OpenAPI or AsyncAPI specification's definition.
//
// GET /specs/{specId}/definitions
func (UnimplementedHandler) GetSpecDefinition(ctx context.Context, params GetSpecDefinitionParams) (r GetSpecDefinitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpecFile implements getSpecFile operation.
//
// Gets the contents of an API specification's file.
//
// GET /specs/{specId}/files/{filePath}
func (UnimplementedHandler) GetSpecFile(ctx context.Context, params GetSpecFileParams) (r GetSpecFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpecFiles implements getSpecFiles operation.
//
// Gets all the files in an API specification.
//
// GET /specs/{specId}/files
func (UnimplementedHandler) GetSpecFiles(ctx context.Context, params GetSpecFilesParams) (r GetSpecFilesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpecVersionTag implements getSpecVersionTag operation.
//
// Gets information about a specification's version tag. The response returns a snapshot of a
// specification at a point in time that lets you track changes to your specifications over time.
//
// GET /specs/{specId}/version-tags/{tagId}/files
func (UnimplementedHandler) GetSpecVersionTag(ctx context.Context, params GetSpecVersionTagParams) (r GetSpecVersionTagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpecVersionTags implements getSpecVersionTags operation.
//
// Gets a list of a specification's version tags.
//
// GET /specs/{specId}/version-tags
func (UnimplementedHandler) GetSpecVersionTags(ctx context.Context, params GetSpecVersionTagsParams) (r GetSpecVersionTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaggedEntities implements getTaggedEntities operation.
//
// Gets Postman elements (entities) by a given tag. Tags enable you to organize and search
// [workspaces], [APIs], and [collections] that contain shared tags.
//
// GET /tags/{slug}/entities
//
// [workspaces]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#tagging-a-workspace
// [APIs]: https://learning.postman.com/docs/designing-and-developing-your-api/managing-apis/#tagging-apis
// [collections]: https://learning.postman.com/docs/collections/using-collections/#tagging-a-collection
func (UnimplementedHandler) GetTaggedEntities(ctx context.Context, params GetTaggedEntitiesParams) (r GetTaggedEntitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeam implements getTeam operation.
//
// Gets information about a Postman team.
//
// GET /teams/{teamId}
func (UnimplementedHandler) GetTeam(ctx context.Context, params GetTeamParams) (r GetTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeamAccessRequests implements getTeamAccessRequests operation.
//
// Gets a team's pending access requests.
//
// GET /teams/{teamId}/access-requests
func (UnimplementedHandler) GetTeamAccessRequests(ctx context.Context, params GetTeamAccessRequestsParams) (r GetTeamAccessRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeamSettings implements getTeamSettings operation.
//
// Gets a team's settings.
//
// GET /teams/{teamId}/settings
func (UnimplementedHandler) GetTeamSettings(ctx context.Context, params GetTeamSettingsParams) (r GetTeamSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeamUser implements getTeamUser operation.
//
// Gets information about a user on the Postman team.
//
// GET /users/{userId}
func (UnimplementedHandler) GetTeamUser(ctx context.Context, params GetTeamUserParams) (r GetTeamUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeamUsers implements getTeamUsers operation.
//
// Gets information about all users on the [Postman team].
//
// GET /users
//
// [Postman team]: https://learning.postman.com/docs/collaborating-in-postman/working-with-your-team/collaboration-overview/
func (UnimplementedHandler) GetTeamUsers(ctx context.Context, params GetTeamUsersParams) (r GetTeamUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTeams implements getTeams operation.
//
// Gets all Postman teams in your organization.
//
// GET /teams
func (UnimplementedHandler) GetTeams(ctx context.Context, params GetTeamsParams) (r GetTeamsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspace implements getWorkspace operation.
//
// Gets information about a workspace.
//
// GET /workspaces/{workspaceId}
func (UnimplementedHandler) GetWorkspace(ctx context.Context, params GetWorkspaceParams) (r GetWorkspaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceActivityFeed implements getWorkspaceActivityFeed operation.
//
// Gets a workspace's [activity feed]. Activity feeds return information about who added or removed
// collections, environments, or elements from a workspace, and users that join or leave a workspace.
//
// GET /workspaces/{workspaceId}/activities
//
// [activity feed]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections/#view-workspace-activity
func (UnimplementedHandler) GetWorkspaceActivityFeed(ctx context.Context, params GetWorkspaceActivityFeedParams) (r GetWorkspaceActivityFeedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceGlobalVariables implements getWorkspaceGlobalVariables operation.
//
// Gets a workspace's global [variables]. Global variables enable you to access data between
// collections, requests, scripts, and environments and are available throughout a workspace.
//
// GET /workspaces/{workspaceId}/global-variables
//
// [variables]: https://learning.postman.com/docs/sending-requests/variables/#variable-scopes
func (UnimplementedHandler) GetWorkspaceGlobalVariables(ctx context.Context, params GetWorkspaceGlobalVariablesParams) (r GetWorkspaceGlobalVariablesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceRoles implements getWorkspaceRoles operation.
//
// Gets the roles of users, user groups, and partners in a workspace.
//
// GET /workspaces/{workspaceId}/roles
func (UnimplementedHandler) GetWorkspaceRoles(ctx context.Context, params GetWorkspaceRolesParams) (r GetWorkspaceRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceTags implements getWorkspaceTags operation.
//
// Gets all the tags associated with a workspace.
//
// GET /workspaces/{workspaceId}/tags
func (UnimplementedHandler) GetWorkspaceTags(ctx context.Context, params GetWorkspaceTagsParams) (r GetWorkspaceTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceUpdate implements getWorkspaceUpdate operation.
//
// Gets information about a workspace update.
//
// GET /workspaces/{workspaceId}/updates/{updateId}
func (UnimplementedHandler) GetWorkspaceUpdate(ctx context.Context, params GetWorkspaceUpdateParams) (r GetWorkspaceUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaceUpdates implements getWorkspaceUpdates operation.
//
// Gets a list of workspace updates for the given workspace.
//
// GET /workspaces/{workspaceId}/updates
func (UnimplementedHandler) GetWorkspaceUpdates(ctx context.Context, params GetWorkspaceUpdatesParams) (r GetWorkspaceUpdatesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspaces implements getWorkspaces operation.
//
// Gets all [workspaces]. The response includes your workspaces and any workspaces that you have access
// to.
//
// GET /workspaces
//
// [workspaces]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/
func (UnimplementedHandler) GetWorkspaces(ctx context.Context, params GetWorkspacesParams) (r GetWorkspacesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportOpenApiDefinition implements importOpenApiDefinition operation.
//
// Imports an OpenAPI definition into Postman as a new [Postman Collection].
//
// POST /import/openapi
//
// [Postman Collection]: https://learning.postman.com/docs/getting-started/creating-the-first-collection/
func (UnimplementedHandler) ImportOpenApiDefinition(ctx context.Context, req ImportOpenApiDefinition, params ImportOpenApiDefinitionParams) (r ImportOpenApiDefinitionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrivateNetworkAddRequests implements listPrivateNetworkAddRequests operation.
//
// Gets all requests to add workspaces to your team's [Private API Network].
//
// GET /network/private/network-entity/request/all
//
// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
func (UnimplementedHandler) ListPrivateNetworkAddRequests(ctx context.Context, params ListPrivateNetworkAddRequestsParams) (r ListPrivateNetworkAddRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPrivateNetworkWorkspaces implements listPrivateNetworkWorkspaces operation.
//
// Gets information workspaces added to your team's [Private API Network].
//
// GET /network/private
//
// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
func (UnimplementedHandler) ListPrivateNetworkWorkspaces(ctx context.Context, params ListPrivateNetworkWorkspacesParams) (r ListPrivateNetworkWorkspacesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagePartnerWorkspaceInvites implements managePartnerWorkspaceInvites operation.
//
// Manages invitations and access to your team's [Partner Workspaces]. You can use this endpoint to:.
//
// POST /invitations
//
// [Partner Workspaces]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/partner-workspaces/manage/
func (UnimplementedHandler) ManagePartnerWorkspaceInvites(ctx context.Context, req ManagePartnerWorkspaceInvites) (r ManagePartnerWorkspaceInvitesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManageTeamMemberRoles implements manageTeamMemberRoles operation.
//
// Adds or removes member roles in groups, teams, organizations, as well as individual users' roles.
//
// POST /teams/{teamId}/bulk-members
func (UnimplementedHandler) ManageTeamMemberRoles(ctx context.Context, req *ManageTeamMemberRoles, params ManageTeamMemberRolesParams) (r ManageTeamMemberRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MergeCollectionFork implements mergeCollectionFork operation.
//
// This endpoint is deprecated.
//
// POST /collections/merge
func (UnimplementedHandler) MergeCollectionFork(ctx context.Context, req *MergeCollectionFork) (r MergeCollectionForkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MergeEnvironmentFork implements mergeEnvironmentFork operation.
//
// [Merges] a forked environment back into its parent environment.
//
// POST /environments/{environmentId}/merges
//
// [Merges]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/#merge-changes-from-a-fork
func (UnimplementedHandler) MergeEnvironmentFork(ctx context.Context, req *MergeEnvironmentFork, params MergeEnvironmentForkParams) (r MergeEnvironmentForkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchCollection implements patchCollection operation.
//
// Updates specific collection information, such as its name, events, or its variables. For more
// information, see the [Postman Collection Format documentation].
//
// PATCH /collections/{collectionId}
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) PatchCollection(ctx context.Context, req *UpdateCollection, params PatchCollectionParams) (r PatchCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchEnvironment implements patchEnvironment operation.
//
// Updates specific environment properties, such as its name and variables.
//
// PATCH /environments/{environmentId}
func (UnimplementedHandler) PatchEnvironment(ctx context.Context, req PatchEnvironment, params PatchEnvironmentParams) (r PatchEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchWorkspaceUpdate implements patchWorkspaceUpdate operation.
//
// Updates a workspace update.
//
// PATCH /workspaces/{workspaceId}/updates/{updateId}
func (UnimplementedHandler) PatchWorkspaceUpdate(ctx context.Context, req *UpdateWorkspaceUpdate, params PatchWorkspaceUpdateParams) (r PatchWorkspaceUpdateRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PublishDocumentation implements publishDocumentation operation.
//
// Publishes a collection's documentation. This makes it publicly available to anyone with the link to
// the documentation.
//
// PUT /collections/{collectionId}/public-documentations
func (UnimplementedHandler) PublishDocumentation(ctx context.Context, req *PublishDocumentation, params PublishDocumentationParams) (r PublishDocumentationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PublishMock implements publishMock operation.
//
// Publishes a mock server. Publishing a mock server sets its Access Control configuration setting to
// public.
//
// POST /mocks/{mockId}/publish
func (UnimplementedHandler) PublishMock(ctx context.Context, params PublishMockParams) (r PublishMockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullCollectionChanges implements pullCollectionChanges operation.
//
// Pulls the changes from a parent (source) collection into the forked collection. In the endpoint's
// response:.
//
// PUT /collections/{collectionId}/pulls
func (UnimplementedHandler) PullCollectionChanges(ctx context.Context, params PullCollectionChangesParams) (r PullCollectionChangesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PullEnvironment implements pullEnvironment operation.
//
// [Pulls] the changes from a parent (source) environment into the forked environment.
//
// POST /environments/{environmentUid}/pulls
//
// [Pulls]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/#pull-updates-from-a-parent-element
func (UnimplementedHandler) PullEnvironment(ctx context.Context, req *PullEnvironmentForkChanges, params PullEnvironmentParams) (r PullEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutCollection implements putCollection operation.
//
// Replaces the contents of a collection using the [Postman Collection v2.1.0 schema format]. Include
// the collection's ID values in the request body. If you do not, the endpoint removes the existing
// items and creates new items.
//
// PUT /collections/{collectionId}
//
// [Postman Collection v2.1.0 schema format]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) PutCollection(ctx context.Context, req *ReplaceCollectionData, params PutCollectionParams) (r PutCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutEnvironment implements putEnvironment operation.
//
// Replaces all the contents of an environment with the given information.
//
// PUT /environments/{environmentId}
func (UnimplementedHandler) PutEnvironment(ctx context.Context, req *ReplaceEnvironmentData, params PutEnvironmentParams) (r PutEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveTeamMembers implements removeTeamMembers operation.
//
// Removes entities, such as users or organizations, from your Postman team. On success, this returns
// an HTTP `204 No Content` response.
//
// DELETE /teams/{teamId}/bulk-members
func (UnimplementedHandler) RemoveTeamMembers(ctx context.Context, req *RemoveTeamMembers, params RemoveTeamMembersParams) (r RemoveTeamMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveWorkspaceFromPrivateNetwork implements removeWorkspaceFromPrivateNetwork operation.
//
// Removes a workspace from your team's [Private API Network].
//
// DELETE /network/private/workspace/{workspaceId}
//
// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
func (UnimplementedHandler) RemoveWorkspaceFromPrivateNetwork(ctx context.Context, params RemoveWorkspaceFromPrivateNetworkParams) (r RemoveWorkspaceFromPrivateNetworkRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResolveCommentThread implements resolveCommentThread operation.
//
// Resolves a comment and any associated replies. On success, this returns an HTTP `204 No Content`
// response.
//
// POST /comments-resolutions/{threadId}
func (UnimplementedHandler) ResolveCommentThread(ctx context.Context, params ResolveCommentThreadParams) (r ResolveCommentThreadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RespondPrivateNetworkAddRequest implements respondPrivateNetworkAddRequest operation.
//
// Responds to a user's request to add a workspace to your team's [Private API Network]. Only managers
// can approve or deny a request. Once approved, the workspace will appear in the team's Private API
// Network.
//
// PUT /network/private/network-entity/request/{requestId}
//
// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
func (UnimplementedHandler) RespondPrivateNetworkAddRequest(ctx context.Context, req *RespondPanElementAddRequestBody, params RespondPrivateNetworkAddRequestParams) (r RespondPrivateNetworkAddRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReviewPullRequest implements reviewPullRequest operation.
//
// Updates the [review] status of a pull request.
//
// POST /pull-requests/{pullRequestId}/tasks
//
// [review]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/reviewing-pull-requests/
func (UnimplementedHandler) ReviewPullRequest(ctx context.Context, req *ReviewPullRequest, params ReviewPullRequestParams) (r ReviewPullRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeOauthToken implements revokeOauthToken operation.
//
// Revokes an active OAuth 2.0 access token and prevents further use of it for authentication. Once
// revoked, the token can't be used for any API requests.
//
// POST /oauth2/token/revoke
func (UnimplementedHandler) RevokeOauthToken(ctx context.Context, req *RevokeOauthToken) (r RevokeOauthTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RunMonitor implements runMonitor operation.
//
// Runs a monitor and returns its run results.
//
// POST /monitors/{monitorId}/run
func (UnimplementedHandler) RunMonitor(ctx context.Context, params RunMonitorParams) (r RunMonitorRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SchemaSecurityValidation implements schemaSecurityValidation operation.
//
// Performs an analysis on the given definition and returns any issues based on your
// [predefined rulesets]. This endpoint can help you understand the violations' impact and offers
// solutions to help you resolve any errors. You can include this endpoint to your CI/CD process to
// automate schema validation.
//
// POST /security/api-validation
//
// [predefined rulesets]: https://learning.postman.com/docs/api-governance/configurable-rules/configurable-rules-overview/
func (UnimplementedHandler) SchemaSecurityValidation(ctx context.Context, req *SchemaValidationRequestBody) (r SchemaSecurityValidationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchPostmanResources implements searchPostmanResources operation.
//
// Searches Postman for resources such as workspaces, collections, requests, and other resource types.
// You can filter results by ownership, visibility, tags, and other criteria.
//
// POST /search
func (UnimplementedHandler) SearchPostmanResources(ctx context.Context, req *SearchPostmanResources, params SearchPostmanResourcesParams) (r SearchPostmanResourcesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncCollectionWithSpec implements syncCollectionWithSpec operation.
//
// Syncs a collection generated from an API specification. This is an asynchronous endpoint that
// returns an HTTP `202 Accepted` response.
//
// PUT /collections/{collectionUid}/synchronizations
func (UnimplementedHandler) SyncCollectionWithSpec(ctx context.Context, params SyncCollectionWithSpecParams) (r SyncCollectionWithSpecRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncSpecWithCollection implements syncSpecWithCollection operation.
//
// Syncs an API specification linked to a collection. This is an asynchronous endpoint that returns an
// HTTP `202 Accepted` response.
//
// PUT /specs/{specId}/synchronizations
func (UnimplementedHandler) SyncSpecWithCollection(ctx context.Context, params SyncSpecWithCollectionParams) (r SyncSpecWithCollectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransferCollectionFolders implements transferCollectionFolders operation.
//
// Copies or moves folders into a collection or folder.
//
// POST /collection-folders-transfers
func (UnimplementedHandler) TransferCollectionFolders(ctx context.Context, req *TransferCollectionItems) (r TransferCollectionFoldersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransferCollectionRequests implements transferCollectionRequests operation.
//
// Copies or moves requests into a collection or folder.
//
// POST /collection-requests-transfers
func (UnimplementedHandler) TransferCollectionRequests(ctx context.Context, req *TransferCollectionItems) (r TransferCollectionRequestsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransferCollectionResponses implements transferCollectionResponses operation.
//
// Copies or moves responses into a request.
//
// POST /collection-responses-transfers
func (UnimplementedHandler) TransferCollectionResponses(ctx context.Context, req *TransferCollectionItems) (r TransferCollectionResponsesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransferWorkspaceElement implements transferWorkspaceElement operation.
//
// Transfers a [Postman element] from one workspace to another workspace. Supported elements include
// collections, environments, mocks, monitors, and Flows modules and actions.
//
// POST /workspaces/{workspaceId}/element-transfers
//
// [Postman element]: https://learning.postman.com/docs/getting-started/basics/postman-elements/
func (UnimplementedHandler) TransferWorkspaceElement(ctx context.Context, req *TransferWorkspaceElement, params TransferWorkspaceElementParams) (r TransferWorkspaceElementRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransferWorkspaceToTeam implements transferWorkspaceToTeam operation.
//
// Transfers a workspace from one team (`source`) to another team (`destination`).
//
// PATCH /workspaces/{workspaceId}/transfers
func (UnimplementedHandler) TransferWorkspaceToTeam(ctx context.Context, req *TransferWorkspaceToTeam, params TransferWorkspaceToTeamParams) (r TransferWorkspaceToTeamRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TransformCollectionToOpenApi implements transformCollectionToOpenApi operation.
//
// Transforms an existing Postman Collection into a stringified OpenAPI definition.
//
// GET /collections/{collectionId}/transformations
func (UnimplementedHandler) TransformCollectionToOpenApi(ctx context.Context, params TransformCollectionToOpenApiParams) (r TransformCollectionToOpenApiRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnpublishDocumentation implements unpublishDocumentation operation.
//
// Unpublishes a collection's documentation. On success, this returns an HTTP `204 No Content`
// response.
//
// DELETE /collections/{collectionId}/public-documentations
func (UnimplementedHandler) UnpublishDocumentation(ctx context.Context, params UnpublishDocumentationParams) (r UnpublishDocumentationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UnpublishMock implements unpublishMock operation.
//
// Unpublishes a mock server. Unpublishing a mock server sets its Access Control configuration setting
// to private.
//
// DELETE /mocks/{mockId}/unpublish
func (UnimplementedHandler) UnpublishMock(ctx context.Context, params UnpublishMockParams) (r UnpublishMockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCollectionComment implements updateCollectionComment operation.
//
// Updates a comment on a collection.
//
// PUT /collections/{collectionId}/comments/{commentId}
func (UnimplementedHandler) UpdateCollectionComment(ctx context.Context, req *CommentUpdate, params UpdateCollectionCommentParams) (r UpdateCollectionCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCollectionFolder implements updateCollectionFolder operation.
//
// Updates a folder in a collection. For a complete list of properties, refer to the Folder entry in
// the [Postman Collection Format documentation].
//
// PUT /collections/{collectionId}/folders/{folderId}
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) UpdateCollectionFolder(ctx context.Context, req *UpdateFolder, params UpdateCollectionFolderParams) (r UpdateCollectionFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCollectionRequest implements updateCollectionRequest operation.
//
// Updates a request in a collection. For a complete list of properties, refer to the Request entry in
// the [Postman Collection Format documentation].
//
// PUT /collections/{collectionId}/requests/{requestId}
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) UpdateCollectionRequest(ctx context.Context, req *UpdateRequest, params UpdateCollectionRequestParams) (r UpdateCollectionRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCollectionResponse implements updateCollectionResponse operation.
//
// Updates a response in a collection. For a complete list of properties, see the
// [Postman Collection Format documentation].
//
// PUT /collections/{collectionId}/responses/{responseId}
//
// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
func (UnimplementedHandler) UpdateCollectionResponse(ctx context.Context, req *UpdateCollectionResponse1, params UpdateCollectionResponseParams) (r UpdateCollectionResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCollectionRoles implements updateCollectionRoles operation.
//
// Updates the roles of users, groups, or teams in a collection. On success, this returns an HTTP
// `204 No Content` response.
//
// PATCH /collections/{collectionId}/roles
func (UnimplementedHandler) UpdateCollectionRoles(ctx context.Context, req *UpdateCollectionRoles, params UpdateCollectionRolesParams) (r UpdateCollectionRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCollectionTags implements updateCollectionTags operation.
//
// Updates a collection's associated tags. This endpoint replaces all existing tags with those you pass
// in the request body.
//
// PUT /collections/{collectionId}/tags
func (UnimplementedHandler) UpdateCollectionTags(ctx context.Context, req *UpdateTags, params UpdateCollectionTagsParams) (r UpdateCollectionTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateComponent implements updateComponent operation.
//
// Updates a component: - `name` — Rename the component. The new name must be unique within the team.
// Archived components can't be renamed.
//
// PATCH /components/{componentId}
func (UnimplementedHandler) UpdateComponent(ctx context.Context, req *UpdateComponentReq, params UpdateComponentParams) (r UpdateComponentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateComponentDraft implements updateComponentDraft operation.
//
// Updates a component's draft. Component drafts contain unpublished edits to a component, which may be
// different from a recently published version.
//
// PATCH /components/{componentId}/drafts
func (UnimplementedHandler) UpdateComponentDraft(ctx context.Context, req *UpdateComponentDraft, params UpdateComponentDraftParams) (r UpdateComponentDraftRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDetectedSecretResolutions implements updateDetectedSecretResolutions operation.
//
// Updates the resolution status of a secret detected in a workspace.
//
// PUT /detected-secrets/{secretId}
func (UnimplementedHandler) UpdateDetectedSecretResolutions(ctx context.Context, req *UpdateSecretResolutionRequest, params UpdateDetectedSecretResolutionsParams) (r UpdateDetectedSecretResolutionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFolderComment implements updateFolderComment operation.
//
// Updates a comment on a folder.
//
// PUT /collections/{collectionId}/folders/{folderId}/comments/{commentId}
func (UnimplementedHandler) UpdateFolderComment(ctx context.Context, req *CommentUpdate, params UpdateFolderCommentParams) (r UpdateFolderCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMock implements updateMock operation.
//
// Updates a mock server's properties, such as its name or collection.
//
// PUT /mocks/{mockId}
func (UnimplementedHandler) UpdateMock(ctx context.Context, req *UpdateMock, params UpdateMockParams) (r UpdateMockRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMockServerResponse implements updateMockServerResponse operation.
//
// Updates a server response.
//
// PUT /mocks/{mockId}/server-responses/{serverResponseId}
func (UnimplementedHandler) UpdateMockServerResponse(ctx context.Context, req *UpdateMockServerResponse, params UpdateMockServerResponseParams) (r UpdateMockServerResponseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMonitor implements updateMonitor operation.
//
// Updates a monitor's [configurations].
//
// PUT /monitors/{monitorId}
//
// [configurations]: https://learning.postman.com/docs/monitoring-your-api/setting-up-monitor/#configure-a-monitor
func (UnimplementedHandler) UpdateMonitor(ctx context.Context, req *UpdateMonitor, params UpdateMonitorParams) (r UpdateMonitorRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePanElementOrFolder implements updatePanElementOrFolder operation.
//
// This endpoint is deprecated.
//
// PUT /network/private/workspace/{workspaceId}
func (UnimplementedHandler) UpdatePanElementOrFolder(ctx context.Context, req *UpdatePanElementOrFolderRequest, params UpdatePanElementOrFolderParams) (r UpdatePanElementOrFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePullRequest implements updatePullRequest operation.
//
// Updates an open pull request.
//
// PUT /pull-requests/{pullRequestId}
func (UnimplementedHandler) UpdatePullRequest(ctx context.Context, req *UpdatePullRequest, params UpdatePullRequestParams) (r UpdatePullRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRequestComment implements updateRequestComment operation.
//
// Updates a comment on a request.
//
// PUT /collections/{collectionId}/requests/{requestId}/comments/{commentId}
func (UnimplementedHandler) UpdateRequestComment(ctx context.Context, req *CommentUpdate, params UpdateRequestCommentParams) (r UpdateRequestCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateResponseComment implements updateResponseComment operation.
//
// Updates a comment on a response.
//
// PUT /collections/{collectionId}/responses/{responseId}/comments/{commentId}
func (UnimplementedHandler) UpdateResponseComment(ctx context.Context, req *CommentUpdate, params UpdateResponseCommentParams) (r UpdateResponseCommentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSdkGitConnection implements updateSdkGitConnection operation.
//
// Updates the Git connection's lifecycle status:.
//
// PUT /sdk-git-connections/{sdkGitConnectionId}
func (UnimplementedHandler) UpdateSdkGitConnection(ctx context.Context, req *UpdateSdkGitConnection, params UpdateSdkGitConnectionParams) (r UpdateSdkGitConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpecFile implements updateSpecFile operation.
//
// Updates a file for an OpenAPI or protobuf 2 or 3 specification.
//
// PATCH /specs/{specId}/files/{filePath}
func (UnimplementedHandler) UpdateSpecFile(ctx context.Context, req *UpdateSpecFile, params UpdateSpecFileParams) (r UpdateSpecFileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpecProperties implements updateSpecProperties operation.
//
// Updates an API specification's properties, such as its name.
//
// PATCH /specs/{specId}
func (UnimplementedHandler) UpdateSpecProperties(ctx context.Context, req *UpdateSpecProperties, params UpdateSpecPropertiesParams) (r UpdateSpecPropertiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSpecSyncOptions implements updateSpecSyncOptions operation.
//
// Updates the [sync options] for a specification's generated collection.
//
// PATCH /specs/{specId}/collections/{collectionId}/sync-options
//
// [sync options]: https://learning.postman.com/docs/design-apis/specifications/generate-collections/#configure-sync-settings
func (UnimplementedHandler) UpdateSpecSyncOptions(ctx context.Context, req *ApiSpecSyncOptions, params UpdateSpecSyncOptionsParams) (r UpdateSpecSyncOptionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTeamSettings implements updateTeamSettings operation.
//
// Updates a team's settings.
//
// PUT /teams/{teamId}/settings
func (UnimplementedHandler) UpdateTeamSettings(ctx context.Context, req *UpdateTeamSettings, params UpdateTeamSettingsParams) (r UpdateTeamSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkspace implements updateWorkspace operation.
//
// Updates a workspace's property, such as its name or visibility.
//
// PUT /workspaces/{workspaceId}
func (UnimplementedHandler) UpdateWorkspace(ctx context.Context, req *UpdateWorkspaceRequest, params UpdateWorkspaceParams) (r UpdateWorkspaceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkspaceGlobalVariables implements updateWorkspaceGlobalVariables operation.
//
// Updates and replaces a workspace's global [variables]. This endpoint replaces all existing global
// variables with the variables you pass in the request body.
//
// PUT /workspaces/{workspaceId}/global-variables
//
// [variables]: https://learning.postman.com/docs/sending-requests/variables/#variable-scopes
func (UnimplementedHandler) UpdateWorkspaceGlobalVariables(ctx context.Context, req *UpdateGlobalVariables, params UpdateWorkspaceGlobalVariablesParams) (r UpdateWorkspaceGlobalVariablesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkspaceRoles implements updateWorkspaceRoles operation.
//
// Updates the roles of users, [user groups], or partners in a workspace. To get a list of roles, use
// the GET `/workspace-roles` endpoint. To get a group ID, use the GET `/groups` endpoint.
//
// PATCH /workspaces/{workspaceId}/roles
//
// [user groups]: https://learning.postman.com/docs/collaborating-in-postman/user-groups/
func (UnimplementedHandler) UpdateWorkspaceRoles(ctx context.Context, req *UpdateWorkspaceRoles, params UpdateWorkspaceRolesParams) (r UpdateWorkspaceRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkspaceTags implements updateWorkspaceTags operation.
//
// Updates a workspace's associated tags. This endpoint replaces all existing tags with those you pass
// in the request body.
//
// PUT /workspaces/{workspaceId}/tags
func (UnimplementedHandler) UpdateWorkspaceTags(ctx context.Context, req *UpdateTags, params UpdateWorkspaceTagsParams) (r UpdateWorkspaceTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}
