// Code generated by ogen, DO NOT EDIT.
package api

type AddWorkspaceToPrivateNetworkRes interface {
	addWorkspaceToPrivateNetworkRes()
}

type ApproveDenyAccessRequestRes interface {
	approveDenyAccessRequestRes()
}

type AsyncMergePullCollectionForkRes interface {
	asyncMergePullCollectionForkRes()
}

type AsyncMergePullCollectionTaskStatusRes interface {
	asyncMergePullCollectionTaskStatusRes()
}

type CreateAccessRequestRes interface {
	createAccessRequestRes()
}

type CreateCollectionCommentRes interface {
	createCollectionCommentRes()
}

type CreateCollectionFolderRes interface {
	createCollectionFolderRes()
}

type CreateCollectionForkRes interface {
	createCollectionForkRes()
}

type CreateCollectionPullRequestRes interface {
	createCollectionPullRequestRes()
}

type CreateCollectionRequestRes interface {
	createCollectionRequestRes()
}

type CreateCollectionRes interface {
	createCollectionRes()
}

type CreateCollectionResponseRes interface {
	createCollectionResponseRes()
}

type CreateComponentRes interface {
	createComponentRes()
}

type CreateComponentVersionRes interface {
	createComponentVersionRes()
}

type CreateEnvironmentRes interface {
	createEnvironmentRes()
}

type CreateFolderCommentRes interface {
	createFolderCommentRes()
}

type CreateMockRes interface {
	createMockRes()
}

type CreateMockServerResponseRes interface {
	createMockServerResponseRes()
}

type CreateMonitorRes interface {
	createMonitorRes()
}

type CreateRequestCommentRes interface {
	createRequestCommentRes()
}

type CreateResponseCommentRes interface {
	createResponseCommentRes()
}

type CreateSdkGitConnectionRes interface {
	createSdkGitConnectionRes()
}

type CreateSdkRes interface {
	createSdkRes()
}

type CreateSpecFileRes interface {
	createSpecFileRes()
}

type CreateSpecRes interface {
	createSpecRes()
}

type CreateSpecVersionTagRes interface {
	createSpecVersionTagRes()
}

type CreateTeamRes interface {
	createTeamRes()
}

type CreateWebhookRes interface {
	createWebhookRes()
}

type CreateWorkspaceRes interface {
	createWorkspaceRes()
}

type CreateWorkspaceUpdateRes interface {
	createWorkspaceUpdateRes()
}

type DeleteCollectionAccessKeyRes interface {
	deleteCollectionAccessKeyRes()
}

type DeleteCollectionCommentRes interface {
	deleteCollectionCommentRes()
}

type DeleteCollectionFolderRes interface {
	deleteCollectionFolderRes()
}

type DeleteCollectionRequestRes interface {
	deleteCollectionRequestRes()
}

type DeleteCollectionRes interface {
	deleteCollectionRes()
}

type DeleteCollectionResponseRes interface {
	deleteCollectionResponseRes()
}

type DeleteEnvironmentRes interface {
	deleteEnvironmentRes()
}

type DeleteFolderCommentRes interface {
	deleteFolderCommentRes()
}

type DeleteMockRes interface {
	deleteMockRes()
}

type DeleteMockServerResponseRes interface {
	deleteMockServerResponseRes()
}

type DeleteMonitorRes interface {
	deleteMonitorRes()
}

type DeleteRequestCommentRes interface {
	deleteRequestCommentRes()
}

type DeleteResponseCommentRes interface {
	deleteResponseCommentRes()
}

type DeleteSdkRes interface {
	deleteSdkRes()
}

type DeleteSpecFileRes interface {
	deleteSpecFileRes()
}

type DeleteSpecRes interface {
	deleteSpecRes()
}

type DeleteWorkspaceRes interface {
	deleteWorkspaceRes()
}

type DeleteWorkspaceUpdateRes interface {
	deleteWorkspaceUpdateRes()
}

type DetectedSecretsQueriesRes interface {
	detectedSecretsQueriesRes()
}

type DuplicateCollectionRes interface {
	duplicateCollectionRes()
}

type ForkEnvironmentRes interface {
	forkEnvironmentRes()
}

type GenerateCollectionRes interface {
	generateCollectionRes()
}

type GenerateOauthTokenRes interface {
	generateOauthTokenRes()
}

type GenerateServiceAccountTokenRes interface {
	generateServiceAccountTokenRes()
}

type GenerateSpecFromCollectionRes interface {
	generateSpecFromCollectionRes()
}

type GenerateToolRes interface {
	generateToolRes()
}

type GetAccountInvoicesRes interface {
	getAccountInvoicesRes()
}

type GetAccountsRes interface {
	getAccountsRes()
}

type GetAllComponentsRes interface {
	getAllComponentsRes()
}

type GetAllSpecsRes interface {
	getAllSpecsRes()
}

type GetAllWorkspaceRolesRes interface {
	getAllWorkspaceRolesRes()
}

type GetAnalyticsDataRes interface {
	getAnalyticsDataRes()
}

type GetAnalyticsMetadataRes interface {
	getAnalyticsMetadataRes()
}

type GetAsyncSpecTaskStatusRes interface {
	getAsyncSpecTaskStatusRes()
}

type GetAuditLogEventActionsRes interface {
	getAuditLogEventActionsRes()
}

type GetAuditLogsRes interface {
	getAuditLogsRes()
}

type GetAuthenticatedUserRes interface {
	getAuthenticatedUserRes()
}

type GetCollectionAccessKeysRes interface {
	getCollectionAccessKeysRes()
}

type GetCollectionCommentsRes interface {
	getCollectionCommentsRes()
}

type GetCollectionFolderRes interface {
	getCollectionFolderRes()
}

type GetCollectionForksRes interface {
	getCollectionForksRes()
}

type GetCollectionPullRequestsRes interface {
	getCollectionPullRequestsRes()
}

type GetCollectionRequestRes interface {
	getCollectionRequestRes()
}

type GetCollectionRes interface {
	getCollectionRes()
}

type GetCollectionResponseRes interface {
	getCollectionResponseRes()
}

type GetCollectionRolesRes interface {
	getCollectionRolesRes()
}

type GetCollectionTagsRes interface {
	getCollectionTagsRes()
}

type GetCollectionUpdatesTasksRes interface {
	getCollectionUpdatesTasksRes()
}

type GetCollectionsForkedByUserRes interface {
	getCollectionsForkedByUserRes()
}

type GetCollectionsRes interface {
	getCollectionsRes()
}

type GetComponentDraftRes interface {
	getComponentDraftRes()
}

type GetComponentRes interface {
	getComponentRes()
}

type GetComponentVersionRes interface {
	getComponentVersionRes()
}

type GetComponentVersionsRes interface {
	getComponentVersionsRes()
}

type GetDetectedSecretsLocationsRes interface {
	getDetectedSecretsLocationsRes()
}

type GetDuplicateCollectionTaskStatusRes interface {
	getDuplicateCollectionTaskStatusRes()
}

type GetEnvironmentForksRes interface {
	getEnvironmentForksRes()
}

type GetEnvironmentRes interface {
	getEnvironmentRes()
}

type GetEnvironmentsRes interface {
	getEnvironmentsRes()
}

type GetFolderCommentsRes interface {
	getFolderCommentsRes()
}

type GetGeneratedCollectionSpecsRes interface {
	getGeneratedCollectionSpecsRes()
}

type GetGroupRes interface {
	getGroupRes()
}

type GetGroupsRes interface {
	getGroupsRes()
}

type GetMockCallLogsRes interface {
	getMockCallLogsRes()
}

type GetMockRes interface {
	getMockRes()
}

type GetMockServerResponseRes interface {
	getMockServerResponseRes()
}

type GetMockServerResponsesRes interface {
	getMockServerResponsesRes()
}

type GetMocksRes interface {
	getMocksRes()
}

type GetMonitorRes interface {
	getMonitorRes()
}

type GetMonitorsRes interface {
	getMonitorsRes()
}

type GetPullRequestRes interface {
	getPullRequestRes()
}

type GetRequestCommentsRes interface {
	getRequestCommentsRes()
}

type GetResponseCommentsRes interface {
	getResponseCommentsRes()
}

type GetRunnerInstancesRes interface {
	getRunnerInstancesRes()
}

type GetRunnerMetricsRes interface {
	getRunnerMetricsRes()
}

type GetSdkDownloadUrlRes interface {
	getSdkDownloadUrlRes()
}

type GetSdkGitConnectionPullRequestsRes interface {
	getSdkGitConnectionPullRequestsRes()
}

type GetSdkGitConnectionRes interface {
	getSdkGitConnectionRes()
}

type GetSdkGitConnectionsRes interface {
	getSdkGitConnectionsRes()
}

type GetSdkRes interface {
	getSdkRes()
}

type GetSdksRes interface {
	getSdksRes()
}

type GetSecretTypesRes interface {
	getSecretTypesRes()
}

type GetSourceCollectionStatusRes interface {
	getSourceCollectionStatusRes()
}

type GetSpecCollectionsRes interface {
	getSpecCollectionsRes()
}

type GetSpecDefinitionRes interface {
	getSpecDefinitionRes()
}

type GetSpecFileRes interface {
	getSpecFileRes()
}

type GetSpecFilesRes interface {
	getSpecFilesRes()
}

type GetSpecRes interface {
	getSpecRes()
}

type GetSpecVersionTagRes interface {
	getSpecVersionTagRes()
}

type GetSpecVersionTagsRes interface {
	getSpecVersionTagsRes()
}

type GetTaggedEntitiesRes interface {
	getTaggedEntitiesRes()
}

type GetTeamAccessRequestsRes interface {
	getTeamAccessRequestsRes()
}

type GetTeamRes interface {
	getTeamRes()
}

type GetTeamSettingsRes interface {
	getTeamSettingsRes()
}

type GetTeamUserRes interface {
	getTeamUserRes()
}

type GetTeamUsersRes interface {
	getTeamUsersRes()
}

type GetTeamsRes interface {
	getTeamsRes()
}

type GetWorkspaceActivityFeedRes interface {
	getWorkspaceActivityFeedRes()
}

type GetWorkspaceGlobalVariablesRes interface {
	getWorkspaceGlobalVariablesRes()
}

type GetWorkspaceRes interface {
	getWorkspaceRes()
}

type GetWorkspaceRolesRes interface {
	getWorkspaceRolesRes()
}

type GetWorkspaceTagsRes interface {
	getWorkspaceTagsRes()
}

type GetWorkspaceUpdateRes interface {
	getWorkspaceUpdateRes()
}

type GetWorkspaceUpdatesRes interface {
	getWorkspaceUpdatesRes()
}

type GetWorkspacesRes interface {
	getWorkspacesRes()
}

type ImportOpenApiDefinitionRes interface {
	importOpenApiDefinitionRes()
}

type ListPrivateNetworkAddRequestsRes interface {
	listPrivateNetworkAddRequestsRes()
}

type ListPrivateNetworkWorkspacesRes interface {
	listPrivateNetworkWorkspacesRes()
}

type ManagePartnerWorkspaceInvitesRes interface {
	managePartnerWorkspaceInvitesRes()
}

type ManageTeamMemberRolesRes interface {
	manageTeamMemberRolesRes()
}

type MergeCollectionForkRes interface {
	mergeCollectionForkRes()
}

type MergeEnvironmentForkRes interface {
	mergeEnvironmentForkRes()
}

type PatchCollectionRes interface {
	patchCollectionRes()
}

type PatchEnvironmentRes interface {
	patchEnvironmentRes()
}

type PatchWorkspaceUpdateRes interface {
	patchWorkspaceUpdateRes()
}

type PublishDocumentationRes interface {
	publishDocumentationRes()
}

type PublishMockRes interface {
	publishMockRes()
}

type PullCollectionChangesRes interface {
	pullCollectionChangesRes()
}

type PullEnvironmentRes interface {
	pullEnvironmentRes()
}

type PutCollectionRes interface {
	putCollectionRes()
}

type PutEnvironmentRes interface {
	putEnvironmentRes()
}

type RemoveTeamMembersRes interface {
	removeTeamMembersRes()
}

type RemoveWorkspaceFromPrivateNetworkRes interface {
	removeWorkspaceFromPrivateNetworkRes()
}

type ResolveCommentThreadRes interface {
	resolveCommentThreadRes()
}

type RespondPrivateNetworkAddRequestRes interface {
	respondPrivateNetworkAddRequestRes()
}

type ReviewPullRequestRes interface {
	reviewPullRequestRes()
}

type RevokeOauthTokenRes interface {
	revokeOauthTokenRes()
}

type RunMonitorRes interface {
	runMonitorRes()
}

type SchemaSecurityValidationRes interface {
	schemaSecurityValidationRes()
}

type SearchPostmanResourcesRes interface {
	searchPostmanResourcesRes()
}

type SyncCollectionWithSpecRes interface {
	syncCollectionWithSpecRes()
}

type SyncSpecWithCollectionRes interface {
	syncSpecWithCollectionRes()
}

type TransferCollectionFoldersRes interface {
	transferCollectionFoldersRes()
}

type TransferCollectionRequestsRes interface {
	transferCollectionRequestsRes()
}

type TransferCollectionResponsesRes interface {
	transferCollectionResponsesRes()
}

type TransferWorkspaceElementRes interface {
	transferWorkspaceElementRes()
}

type TransferWorkspaceToTeamRes interface {
	transferWorkspaceToTeamRes()
}

type TransformCollectionToOpenApiRes interface {
	transformCollectionToOpenApiRes()
}

type UnpublishDocumentationRes interface {
	unpublishDocumentationRes()
}

type UnpublishMockRes interface {
	unpublishMockRes()
}

type UpdateCollectionCommentRes interface {
	updateCollectionCommentRes()
}

type UpdateCollectionFolderRes interface {
	updateCollectionFolderRes()
}

type UpdateCollectionRequestRes interface {
	updateCollectionRequestRes()
}

type UpdateCollectionResponseRes interface {
	updateCollectionResponseRes()
}

type UpdateCollectionRolesRes interface {
	updateCollectionRolesRes()
}

type UpdateCollectionTagsRes interface {
	updateCollectionTagsRes()
}

type UpdateComponentDraftRes interface {
	updateComponentDraftRes()
}

type UpdateComponentRes interface {
	updateComponentRes()
}

type UpdateDetectedSecretResolutionsRes interface {
	updateDetectedSecretResolutionsRes()
}

type UpdateFolderCommentRes interface {
	updateFolderCommentRes()
}

type UpdateMockRes interface {
	updateMockRes()
}

type UpdateMockServerResponseRes interface {
	updateMockServerResponseRes()
}

type UpdateMonitorRes interface {
	updateMonitorRes()
}

type UpdatePanElementOrFolderRes interface {
	updatePanElementOrFolderRes()
}

type UpdatePullRequestRes interface {
	updatePullRequestRes()
}

type UpdateRequestCommentRes interface {
	updateRequestCommentRes()
}

type UpdateResponseCommentRes interface {
	updateResponseCommentRes()
}

type UpdateSdkGitConnectionRes interface {
	updateSdkGitConnectionRes()
}

type UpdateSpecFileRes interface {
	updateSpecFileRes()
}

type UpdateSpecPropertiesRes interface {
	updateSpecPropertiesRes()
}

type UpdateSpecSyncOptionsRes interface {
	updateSpecSyncOptionsRes()
}

type UpdateTeamSettingsRes interface {
	updateTeamSettingsRes()
}

type UpdateWorkspaceGlobalVariablesRes interface {
	updateWorkspaceGlobalVariablesRes()
}

type UpdateWorkspaceRes interface {
	updateWorkspaceRes()
}

type UpdateWorkspaceRolesRes interface {
	updateWorkspaceRolesRes()
}

type UpdateWorkspaceTagsRes interface {
	updateWorkspaceTagsRes()
}
