// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddWorkspaceToPrivateNetwork implements addWorkspaceToPrivateNetwork operation.
	//
	// Publishes a workspace in your team's [Private API Network].
	//
	// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
	//
	// POST /network/private
	AddWorkspaceToPrivateNetwork(ctx context.Context, req *AddWorkspace) (AddWorkspaceToPrivateNetworkRes, error)
	// ApproveDenyAccessRequest implements approveDenyAccessRequest operation.
	//
	// Approve or deny a team's access request.
	//
	// POST /teams/{teamId}/access-requests/{requestId}
	ApproveDenyAccessRequest(ctx context.Context, req *ApproveDenyAccessRequest, params ApproveDenyAccessRequestParams) (ApproveDenyAccessRequestRes, error)
	// AsyncMergePullCollectionFork implements asyncMergePullCollectionFork operation.
	//
	// [Merges] a forked (source) collection and its parent (destination) collection asynchronously. To
	// pull changes into a fork, pass the forked collection's ID as the `destination` value and the parent
	// collection ID as the `source` value.
	//
	// [Merges]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/#merge-changes-from-a-fork
	//
	// PUT /collection-merges
	AsyncMergePullCollectionFork(ctx context.Context, req *MergePullCollectionChanges) (AsyncMergePullCollectionForkRes, error)
	// AsyncMergePullCollectionTaskStatus implements asyncMergePullCollectionTaskStatus operation.
	//
	// Gets the status of a collection's merge or a pull changes task.
	//
	// GET /collection-merges-tasks/{taskId}
	AsyncMergePullCollectionTaskStatus(ctx context.Context, params AsyncMergePullCollectionTaskStatusParams) (AsyncMergePullCollectionTaskStatusRes, error)
	// CreateAccessRequest implements createAccessRequest operation.
	//
	// Creates an access request for a team. Access requests include actions such as request to join a
	// team, upgrading a user's role, adding members, and requesting team role access to another team.
	//
	// POST /teams/{teamId}/access-requests
	CreateAccessRequest(ctx context.Context, req *CreateAccessRequest, params CreateAccessRequestParams) (CreateAccessRequestRes, error)
	// CreateCollection implements createCollection operation.
	//
	// Creates a collection using the [Postman Collection v2.1.0 schema format].
	//
	// [Postman Collection v2.1.0 schema format]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// POST /collections
	CreateCollection(ctx context.Context, req *CreateCollection, params CreateCollectionParams) (CreateCollectionRes, error)
	// CreateCollectionComment implements createCollectionComment operation.
	//
	// Creates a comment on a collection. To create a reply on an existing comment, include the `threadId`
	// property in the request body.
	//
	// POST /collections/{collectionId}/comments
	CreateCollectionComment(ctx context.Context, req *CommentCreate, params CreateCollectionCommentParams) (CreateCollectionCommentRes, error)
	// CreateCollectionFolder implements createCollectionFolder operation.
	//
	// Creates a folder in a collection. For a complete list of properties, refer to the Folder entry in
	// the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// POST /collections/{collectionId}/folders
	CreateCollectionFolder(ctx context.Context, req *CreateFolder, params CreateCollectionFolderParams) (CreateCollectionFolderRes, error)
	// CreateCollectionFork implements createCollectionFork operation.
	//
	// Creates a [fork] from an existing collection into a workspace.
	//
	// [fork]: https://learning.postman.com/docs/collaborating-in-postman/version-control/#creating-a-fork
	//
	// POST /collections/fork/{collectionId}
	CreateCollectionFork(ctx context.Context, req *CreateCollectionFork, params CreateCollectionForkParams) (CreateCollectionForkRes, error)
	// CreateCollectionPullRequest implements createCollectionPullRequest operation.
	//
	// Creates a pull request for a forked collection into its parent collection.
	//
	// POST /collections/{collectionId}/pull-requests
	CreateCollectionPullRequest(ctx context.Context, req *CreatePullRequest, params CreateCollectionPullRequestParams) (CreateCollectionPullRequestRes, error)
	// CreateCollectionRequest implements createCollectionRequest operation.
	//
	// Creates a request in a collection. For a complete list of properties, refer to the Request entry in
	// the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// POST /collections/{collectionId}/requests
	CreateCollectionRequest(ctx context.Context, req *CreateRequest, params CreateCollectionRequestParams) (CreateCollectionRequestRes, error)
	// CreateCollectionResponse implements createCollectionResponse operation.
	//
	// Creates a request response in a collection. For a complete list of request body properties, refer to
	// the Response entry in the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// POST /collections/{collectionId}/responses
	CreateCollectionResponse(ctx context.Context, req *CreateCollectionResponseRequest, params CreateCollectionResponseParams) (CreateCollectionResponseRes, error)
	// CreateComponent implements createComponent operation.
	//
	// Creates a new component. The component is created in an active state with an initial draft. Use the
	// POST `/components/{componentId}/versions` endpoint to publish a version.
	//
	// POST /components
	CreateComponent(ctx context.Context, req *CreateComponent) (CreateComponentRes, error)
	// CreateComponentVersion implements createComponentVersion operation.
	//
	// Publishes a new version of a component from the current draft.
	//
	// POST /components/{componentId}/versions
	CreateComponentVersion(ctx context.Context, req *CreateComponentVersion, params CreateComponentVersionParams) (CreateComponentVersionRes, error)
	// CreateEnvironment implements createEnvironment operation.
	//
	// Creates an environment.
	//
	// POST /environments
	CreateEnvironment(ctx context.Context, req *CreateEnvironment, params CreateEnvironmentParams) (CreateEnvironmentRes, error)
	// CreateFolderComment implements createFolderComment operation.
	//
	// Creates a comment on a folder. To create a reply on an existing comment, include the `threadId`
	// property in the request body.
	//
	// POST /collections/{collectionId}/folders/{folderId}/comments
	CreateFolderComment(ctx context.Context, req *CommentCreate, params CreateFolderCommentParams) (CreateFolderCommentRes, error)
	// CreateMock implements createMock operation.
	//
	// Creates a mock server in a collection.
	//
	// POST /mocks
	CreateMock(ctx context.Context, req *CreateMock, params CreateMockParams) (CreateMockRes, error)
	// CreateMockServerResponse implements createMockServerResponse operation.
	//
	// Creates a server response. Server responses let you simulate 5xx server-level responses, such as 500
	// or 503.
	//
	// POST /mocks/{mockId}/server-responses
	CreateMockServerResponse(ctx context.Context, req *CreateMockServerResponse, params CreateMockServerResponseParams) (CreateMockServerResponseRes, error)
	// CreateMonitor implements createMonitor operation.
	//
	// Creates a monitor.
	//
	// POST /monitors
	CreateMonitor(ctx context.Context, req *CreateMonitor, params CreateMonitorParams) (CreateMonitorRes, error)
	// CreateRequestComment implements createRequestComment operation.
	//
	// Creates a comment on a request. To create a reply on an existing comment, include the `threadId`
	// property in the request body.
	//
	// POST /collections/{collectionId}/requests/{requestId}/comments
	CreateRequestComment(ctx context.Context, req *CommentCreate, params CreateRequestCommentParams) (CreateRequestCommentRes, error)
	// CreateResponseComment implements createResponseComment operation.
	//
	// Creates a comment on a response. To create a reply on an existing comment, include the `threadId`
	// property in the request body.
	//
	// POST /collections/{collectionId}/responses/{responseId}/comments
	CreateResponseComment(ctx context.Context, req *CommentCreate, params CreateResponseCommentParams) (CreateResponseCommentRes, error)
	// CreateSdk implements createSdk operation.
	//
	// Creates an asynchronous generation job for a single SDK (in one language) from a collection or
	// specification.
	//
	// POST /sdks
	CreateSdk(ctx context.Context, req *CreateSdk) (CreateSdkRes, error)
	// CreateSdkGitConnection implements createSdkGitConnection operation.
	//
	// Connects a Postman source element (collection or specification) to a Git repository for one SDK
	// language. This creates a new connection in the`active` state.
	//
	// POST /sdk-git-connections
	CreateSdkGitConnection(ctx context.Context, req *CreateSdkGitConnection) (CreateSdkGitConnectionRes, error)
	// CreateSpec implements createSpec operation.
	//
	// Creates an API specification in Postman's [Spec Hub]. Specifications can be single or multi-file.
	//
	// [Spec Hub]: https://learning.postman.com/docs/design-apis/specifications/overview/
	//
	// POST /specs
	CreateSpec(ctx context.Context, req *CreateSpec, params CreateSpecParams) (CreateSpecRes, error)
	// CreateSpecFile implements createSpecFile operation.
	//
	// Creates a file for an OpenAPI or a protobuf 2 or 3 specification.
	//
	// POST /specs/{specId}/files
	CreateSpecFile(ctx context.Context, req *CreateSpecFile, params CreateSpecFileParams) (CreateSpecFileRes, error)
	// CreateSpecVersionTag implements createSpecVersionTag operation.
	//
	// Creates a version tag for a specification. Version tags are snapshots of a specification at a point
	// in time that let you to track changes to your specifications over time.
	//
	// POST /specs/{specId}/version-tags
	CreateSpecVersionTag(ctx context.Context, req *CreateSpecVersionTag, params CreateSpecVersionTagParams) (CreateSpecVersionTagRes, error)
	// CreateTeam implements createTeam operation.
	//
	// [Creates] a Postman team in your organization.
	//
	// [Creates]: https://learning.postman.com/docs/administration/managing-your-team/create-teams/
	//
	// POST /teams
	CreateTeam(ctx context.Context, req *CreateTeam) (CreateTeamRes, error)
	// CreateWebhook implements createWebhook operation.
	//
	// Creates a webhook that triggers a collection with a custom payload. You can get the webhook's URL
	// from the `webhookUrl` property in the endpoint's response.
	//
	// POST /webhooks
	CreateWebhook(ctx context.Context, req *CreateWebhook, params CreateWebhookParams) (CreateWebhookRes, error)
	// CreateWorkspace implements createWorkspace operation.
	//
	// Creates a new [workspace].
	//
	// [workspace]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/
	//
	// POST /workspaces
	CreateWorkspace(ctx context.Context, req *CreateWorkspace) (CreateWorkspaceRes, error)
	// CreateWorkspaceUpdate implements createWorkspaceUpdate operation.
	//
	// Creates a [workspace update] in the given workspace. Workspace updates keep workspace watchers
	// informed about changes, such as new features, bug fixes, breaking changes, and announcements.
	//
	// [workspace update]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/internal-workspaces/workspace-updates
	//
	// POST /workspaces/{workspaceId}/updates
	CreateWorkspaceUpdate(ctx context.Context, req *CreateWorkspaceUpdate, params CreateWorkspaceUpdateParams) (CreateWorkspaceUpdateRes, error)
	// DeleteCollection implements deleteCollection operation.
	//
	// Deletes a collection.
	//
	// DELETE /collections/{collectionId}
	DeleteCollection(ctx context.Context, params DeleteCollectionParams) (DeleteCollectionRes, error)
	// DeleteCollectionAccessKey implements deleteCollectionAccessKey operation.
	//
	// Deletes a collection access key. To get a collection access key's ID, use the GET
	// `/collection-access-key` endpoint.
	//
	// DELETE /collection-access-keys/{keyId}
	DeleteCollectionAccessKey(ctx context.Context, params DeleteCollectionAccessKeyParams) (DeleteCollectionAccessKeyRes, error)
	// DeleteCollectionComment implements deleteCollectionComment operation.
	//
	// Deletes a comment from a collection. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /collections/{collectionId}/comments/{commentId}
	DeleteCollectionComment(ctx context.Context, params DeleteCollectionCommentParams) (DeleteCollectionCommentRes, error)
	// DeleteCollectionFolder implements deleteCollectionFolder operation.
	//
	// Deletes a folder in a collection.
	//
	// DELETE /collections/{collectionId}/folders/{folderId}
	DeleteCollectionFolder(ctx context.Context, params DeleteCollectionFolderParams) (DeleteCollectionFolderRes, error)
	// DeleteCollectionRequest implements deleteCollectionRequest operation.
	//
	// Deletes a request in a collection.
	//
	// DELETE /collections/{collectionId}/requests/{requestId}
	DeleteCollectionRequest(ctx context.Context, params DeleteCollectionRequestParams) (DeleteCollectionRequestRes, error)
	// DeleteCollectionResponse implements deleteCollectionResponse operation.
	//
	// Deletes a response in a collection.
	//
	// DELETE /collections/{collectionId}/responses/{responseId}
	DeleteCollectionResponse(ctx context.Context, params DeleteCollectionResponseParams) (DeleteCollectionResponseRes, error)
	// DeleteEnvironment implements deleteEnvironment operation.
	//
	// Deletes an environment.
	//
	// DELETE /environments/{environmentId}
	DeleteEnvironment(ctx context.Context, params DeleteEnvironmentParams) (DeleteEnvironmentRes, error)
	// DeleteFolderComment implements deleteFolderComment operation.
	//
	// Deletes a comment from a folder. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /collections/{collectionId}/folders/{folderId}/comments/{commentId}
	DeleteFolderComment(ctx context.Context, params DeleteFolderCommentParams) (DeleteFolderCommentRes, error)
	// DeleteMock implements deleteMock operation.
	//
	// Deletes a mock server.
	//
	// DELETE /mocks/{mockId}
	DeleteMock(ctx context.Context, params DeleteMockParams) (DeleteMockRes, error)
	// DeleteMockServerResponse implements deleteMockServerResponse operation.
	//
	// Deletes a mock server's server response.
	//
	// DELETE /mocks/{mockId}/server-responses/{serverResponseId}
	DeleteMockServerResponse(ctx context.Context, params DeleteMockServerResponseParams) (DeleteMockServerResponseRes, error)
	// DeleteMonitor implements deleteMonitor operation.
	//
	// Deletes a monitor.
	//
	// DELETE /monitors/{monitorId}
	DeleteMonitor(ctx context.Context, params DeleteMonitorParams) (DeleteMonitorRes, error)
	// DeleteRequestComment implements deleteRequestComment operation.
	//
	// Deletes a comment from a request. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /collections/{collectionId}/requests/{requestId}/comments/{commentId}
	DeleteRequestComment(ctx context.Context, params DeleteRequestCommentParams) (DeleteRequestCommentRes, error)
	// DeleteResponseComment implements deleteResponseComment operation.
	//
	// Deletes a comment from a response. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /collections/{collectionId}/responses/{responseId}/comments/{commentId}
	DeleteResponseComment(ctx context.Context, params DeleteResponseCommentParams) (DeleteResponseCommentRes, error)
	// DeleteSdk implements deleteSdk operation.
	//
	// Deletes an SDK record and its stored archive. On success, this returns a `204 No Content` response.
	//
	// DELETE /sdks/{sdkId}
	DeleteSdk(ctx context.Context, params DeleteSdkParams) (DeleteSdkRes, error)
	// DeleteSpec implements deleteSpec operation.
	//
	// Deletes an API specification. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /specs/{specId}
	DeleteSpec(ctx context.Context, params DeleteSpecParams) (DeleteSpecRes, error)
	// DeleteSpecFile implements deleteSpecFile operation.
	//
	// Deletes a file in an API specification. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /specs/{specId}/files/{filePath}
	DeleteSpecFile(ctx context.Context, params DeleteSpecFileParams) (DeleteSpecFileRes, error)
	// DeleteWorkspace implements deleteWorkspace operation.
	//
	// Deletes an existing workspace.
	//
	// DELETE /workspaces/{workspaceId}
	DeleteWorkspace(ctx context.Context, params DeleteWorkspaceParams) (DeleteWorkspaceRes, error)
	// DeleteWorkspaceUpdate implements deleteWorkspaceUpdate operation.
	//
	// Deletes a workspace update. On success, this returns an HTTP `204 No Content` response.
	//
	// DELETE /workspaces/{workspaceId}/updates/{updateId}
	DeleteWorkspaceUpdate(ctx context.Context, params DeleteWorkspaceUpdateParams) (DeleteWorkspaceUpdateRes, error)
	// DetectedSecretsQueries implements detectedSecretsQueries operation.
	//
	// Returns all secrets detected by Postman's [Secret Scanner], grouped by workspace or resource. If you
	// pass an empty request body, this endpoint returns all results.
	//
	// [Secret Scanner]: https://learning.postman.com/docs/administration/secret-scanner/
	//
	// POST /detected-secrets-queries
	DetectedSecretsQueries(ctx context.Context, req *DetectedSecretsQueryRequest, params DetectedSecretsQueriesParams) (DetectedSecretsQueriesRes, error)
	// DuplicateCollection implements duplicateCollection operation.
	//
	// Creates a duplicate of the given collection in another workspace.
	//
	// POST /collections/{collectionId}/duplicates
	DuplicateCollection(ctx context.Context, req *DuplicateCollection, params DuplicateCollectionParams) (DuplicateCollectionRes, error)
	// ForkEnvironment implements forkEnvironment operation.
	//
	// Creates a [fork] of an existing environment.
	//
	// [fork]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/
	//
	// POST /environments/{environmentId}/forks
	ForkEnvironment(ctx context.Context, req *ForkEnvironment, params ForkEnvironmentParams) (ForkEnvironmentRes, error)
	// GenerateCollection implements generateCollection operation.
	//
	// Creates a collection from the given OpenAPI 2.0, 3.0, or 3.1 specification or Smithy specification.
	// The response contains a polling link to the task status.
	//
	// POST /specs/{specId}/generations/{elementType}
	GenerateCollection(ctx context.Context, req *GenerateCollection, params GenerateCollectionParams) (GenerateCollectionRes, error)
	// GenerateOauthToken implements generateOauthToken operation.
	//
	// Generates an OAuth 2.0 access token for a client application using the `client_credentials` grant
	// type. Use this endpoint with backend services or bots to authenticate and authorize API requests
	// without user interaction.
	//
	// POST /oauth2/token
	GenerateOauthToken(ctx context.Context, req *GenerateOauthToken) (GenerateOauthTokenRes, error)
	// GenerateServiceAccountToken implements generateServiceAccountToken operation.
	//
	// Exchanges a service account API key for a short-lived access token. On success, the response
	// contains an access token that can be used to authenticate downstream service-to-service requests on
	// behalf of the service account. The token is a JWT that encodes the service account's identity and
	// permissions, and is valid for 15 minutes.
	//
	// POST /service-account-tokens
	GenerateServiceAccountToken(ctx context.Context) (GenerateServiceAccountTokenRes, error)
	// GenerateSpecFromCollection implements generateSpecFromCollection operation.
	//
	// Generates an OpenAPI 2.0, 3.0, or 3.1 specification for the given collection. The response contains
	// a polling link to the task status.
	//
	// POST /collections/{collectionUid}/generations/{elementType}
	GenerateSpecFromCollection(ctx context.Context, req *GenerateSpecFromCollection, params GenerateSpecFromCollectionParams) (GenerateSpecFromCollectionRes, error)
	// GenerateTool implements generateTool operation.
	//
	// This endpoint is deprecated.
	//
	// POST /postbot/generations/tool
	GenerateTool(ctx context.Context, req *GenerateTool) (GenerateToolRes, error)
	// GetAccountInvoices implements getAccountInvoices operation.
	//
	// Gets all invoices for a Postman billing account filtered by the status of the invoice.
	//
	// GET /accounts/{accountId}/invoices
	GetAccountInvoices(ctx context.Context, params GetAccountInvoicesParams) (GetAccountInvoicesRes, error)
	// GetAccounts implements getAccounts operation.
	//
	// Gets Postman billing account details for the given team.
	//
	// GET /accounts
	GetAccounts(ctx context.Context) (GetAccountsRes, error)
	// GetAllComponents implements getAllComponents operation.
	//
	// Gets a list of all components in the team's component library.
	//
	// GET /components
	GetAllComponents(ctx context.Context, params GetAllComponentsParams) (GetAllComponentsRes, error)
	// GetAllSpecs implements getAllSpecs operation.
	//
	// Gets all API specifications in a workspace.
	//
	// GET /specs
	GetAllSpecs(ctx context.Context, params GetAllSpecsParams) (GetAllSpecsRes, error)
	// GetAllWorkspaceRoles implements getAllWorkspaceRoles operation.
	//
	// Gets information about all roles in a workspace, based on the team's [plan].
	//
	// [plan]: https://www.postman.com/pricing/
	//
	// GET /workspaces-roles
	GetAllWorkspaceRoles(ctx context.Context) (GetAllWorkspaceRolesRes, error)
	// GetAnalyticsData implements getAnalyticsData operation.
	//
	// Gets analytics data based on the specified resource, metrics, and given filters for team, internal,
	// and public workspaces, as well as Partner Workspaces.
	//
	// GET /analytics
	GetAnalyticsData(ctx context.Context, params GetAnalyticsDataParams) (GetAnalyticsDataRes, error)
	// GetAnalyticsMetadata implements getAnalyticsMetadata operation.
	//
	// Returns a catalog of analytics resources and their corresponding metrics for use with the GET
	// /analytics endpoint. These metrics provide insights on API usage, success, workspace, and team
	// trends in Postman.
	//
	// GET /analytics-metadata
	GetAnalyticsMetadata(ctx context.Context, params GetAnalyticsMetadataParams) (GetAnalyticsMetadataRes, error)
	// GetAsyncSpecTaskStatus implements getAsyncSpecTaskStatus operation.
	//
	// Gets the status of an asynchronous API specification creation task.
	//
	// GET /{elementType}/{elementId}/tasks/{taskId}
	GetAsyncSpecTaskStatus(ctx context.Context, params GetAsyncSpecTaskStatusParams) (GetAsyncSpecTaskStatusRes, error)
	// GetAuditLogEventActions implements getAuditLogEventActions operation.
	//
	// Gets a complete list of all available audit log event actions.
	//
	// GET /audit-actions
	GetAuditLogEventActions(ctx context.Context) (GetAuditLogEventActionsRes, error)
	// GetAuditLogs implements getAuditLogs operation.
	//
	// Gets a list of your team's generated audit events. For a complete list of all audit events, see
	// [Audit logs].
	//
	// [Audit logs]: https://learning.postman.com/docs/administration/audit-logs/
	//
	// GET /audit/logs
	GetAuditLogs(ctx context.Context, params GetAuditLogsParams) (GetAuditLogsRes, error)
	// GetAuthenticatedUser implements getAuthenticatedUser operation.
	//
	// Gets information about the authenticated user.
	//
	// GET /me
	GetAuthenticatedUser(ctx context.Context) (GetAuthenticatedUserRes, error)
	// GetCollection implements getCollection operation.
	//
	// Gets information about a collection. For a complete list of this endpoint's possible values, refer
	// to the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// GET /collections/{collectionId}
	GetCollection(ctx context.Context, params GetCollectionParams) (GetCollectionRes, error)
	// GetCollectionAccessKeys implements getCollectionAccessKeys operation.
	//
	// Gets the authenticated user's personal and team [collection access keys].
	//
	// [collection access keys]: https://learning.postman.com/docs/developer/postman-api/authentication/#generate-a-collection-access-key
	//
	// GET /collection-access-keys
	GetCollectionAccessKeys(ctx context.Context, params GetCollectionAccessKeysParams) (GetCollectionAccessKeysRes, error)
	// GetCollectionComments implements getCollectionComments operation.
	//
	// Gets all comments left by users in a collection.
	//
	// GET /collections/{collectionId}/comments
	GetCollectionComments(ctx context.Context, params GetCollectionCommentsParams) (GetCollectionCommentsRes, error)
	// GetCollectionFolder implements getCollectionFolder operation.
	//
	// Gets information about a folder in a collection.
	//
	// GET /collections/{collectionId}/folders/{folderId}
	GetCollectionFolder(ctx context.Context, params GetCollectionFolderParams) (GetCollectionFolderRes, error)
	// GetCollectionForks implements getCollectionForks operation.
	//
	// Gets a collection's forked collections. The response returns data for each fork, such as the fork's
	// ID, the user who forked it, and the fork's creation date.
	//
	// GET /collections/{collectionId}/forks
	GetCollectionForks(ctx context.Context, params GetCollectionForksParams) (GetCollectionForksRes, error)
	// GetCollectionPullRequests implements getCollectionPullRequests operation.
	//
	// Gets information about a collection's pull requests, such as the source and destination IDs, status
	// of the pull requests, and a URL link to the pull requests.
	//
	// GET /collections/{collectionId}/pull-requests
	GetCollectionPullRequests(ctx context.Context, params GetCollectionPullRequestsParams) (GetCollectionPullRequestsRes, error)
	// GetCollectionRequest implements getCollectionRequest operation.
	//
	// Gets information about a request in a collection.
	//
	// GET /collections/{collectionId}/requests/{requestId}
	GetCollectionRequest(ctx context.Context, params GetCollectionRequestParams) (GetCollectionRequestRes, error)
	// GetCollectionResponse implements getCollectionResponse operation.
	//
	// Gets information about a response in a collection.
	//
	// GET /collections/{collectionId}/responses/{responseId}
	GetCollectionResponse(ctx context.Context, params GetCollectionResponseParams) (GetCollectionResponseRes, error)
	// GetCollectionRoles implements getCollectionRoles operation.
	//
	// Gets information about all roles in a collection. The response returns the IDs of all users, teams,
	// and groups with access to view or edit the collection.
	//
	// GET /collections/{collectionId}/roles
	GetCollectionRoles(ctx context.Context, params GetCollectionRolesParams) (GetCollectionRolesRes, error)
	// GetCollectionTags implements getCollectionTags operation.
	//
	// Gets all the tags associated with a collection.
	//
	// GET /collections/{collectionId}/tags
	GetCollectionTags(ctx context.Context, params GetCollectionTagsParams) (GetCollectionTagsRes, error)
	// GetCollectionUpdatesTasks implements getCollectionUpdatesTasks operation.
	//
	// Gets the status of an asynchronous collection update task.
	//
	// GET /collection-updates-tasks/{taskId}
	GetCollectionUpdatesTasks(ctx context.Context, params GetCollectionUpdatesTasksParams) (GetCollectionUpdatesTasksRes, error)
	// GetCollections implements getCollections operation.
	//
	// Gets all of your [collections]. The response includes all of your subscribed collections.
	//
	// [collections]: https://www.postman.com/docs/collections
	//
	// GET /collections
	GetCollections(ctx context.Context, params GetCollectionsParams) (GetCollectionsRes, error)
	// GetCollectionsForkedByUser implements getCollectionsForkedByUser operation.
	//
	// Gets a list of all the authenticated user's forked collections.
	//
	// GET /collections/collection-forks
	GetCollectionsForkedByUser(ctx context.Context, params GetCollectionsForkedByUserParams) (GetCollectionsForkedByUserRes, error)
	// GetComponent implements getComponent operation.
	//
	// Gets information about a component. Use the `include` and `expand` query parameters to return
	// additional information, such as `hasVersions` and the latest published version.
	//
	// GET /components/{componentId}
	GetComponent(ctx context.Context, params GetComponentParams) (GetComponentRes, error)
	// GetComponentDraft implements getComponentDraft operation.
	//
	// Gets information about the current working draft of a component, including its content and format.
	// Drafts represent the latest unpublished edits of a component, which may be different from the most
	// recently published version.
	//
	// GET /components/{componentId}/drafts
	GetComponentDraft(ctx context.Context, params GetComponentDraftParams) (GetComponentDraftRes, error)
	// GetComponentVersion implements getComponentVersion operation.
	//
	// Gets a published version of a component.
	//
	// GET /components/{componentId}/versions/{versionId}
	GetComponentVersion(ctx context.Context, params GetComponentVersionParams) (GetComponentVersionRes, error)
	// GetComponentVersions implements getComponentVersions operation.
	//
	// Gets a list of a component's published versions.
	//
	// GET /components/{componentId}/versions
	GetComponentVersions(ctx context.Context, params GetComponentVersionsParams) (GetComponentVersionsRes, error)
	// GetDetectedSecretsLocations implements getDetectedSecretsLocations operation.
	//
	// Gets the locations of secrets detected by Postman's [Secret Scanner].
	//
	// [Secret Scanner]: https://learning.postman.com/docs/administration/secret-scanner/
	//
	// GET /detected-secrets/{secretId}/locations
	GetDetectedSecretsLocations(ctx context.Context, params GetDetectedSecretsLocationsParams) (GetDetectedSecretsLocationsRes, error)
	// GetDuplicateCollectionTaskStatus implements getDuplicateCollectionTaskStatus operation.
	//
	// Gets the status of a collection duplication task.
	//
	// GET /collection-duplicate-tasks/{taskId}
	GetDuplicateCollectionTaskStatus(ctx context.Context, params GetDuplicateCollectionTaskStatusParams) (GetDuplicateCollectionTaskStatusRes, error)
	// GetEnvironment implements getEnvironment operation.
	//
	// Gets information about an environment.
	//
	// GET /environments/{environmentId}
	GetEnvironment(ctx context.Context, params GetEnvironmentParams) (GetEnvironmentRes, error)
	// GetEnvironmentForks implements getEnvironmentForks operation.
	//
	// Gets all of an environment's forked environments.
	//
	// GET /environments/{environmentId}/forks
	GetEnvironmentForks(ctx context.Context, params GetEnvironmentForksParams) (GetEnvironmentForksRes, error)
	// GetEnvironments implements getEnvironments operation.
	//
	// Gets information about all of your [environments].
	//
	// [environments]: https://learning.postman.com/docs/sending-requests/managing-environments/
	//
	// GET /environments
	GetEnvironments(ctx context.Context, params GetEnvironmentsParams) (GetEnvironmentsRes, error)
	// GetFolderComments implements getFolderComments operation.
	//
	// Gets all comments left by users in a folder.
	//
	// GET /collections/{collectionId}/folders/{folderId}/comments
	GetFolderComments(ctx context.Context, params GetFolderCommentsParams) (GetFolderCommentsRes, error)
	// GetGeneratedCollectionSpecs implements getGeneratedCollectionSpecs operation.
	//
	// Migrates an API Builder definition to a [Spec Hub] specification. You can migrate the definition to
	// an existing workspace, or create a new workspace to migrate the definition into. On success, this
	// returns an HTTP `202 Created` response. You can use the GET `/apis/{apiId}/spec-migrations` endpoint
	// to check the migration status.
	//
	// [Spec Hub]: https://learning.postman.com/docs/design-apis/specifications/overview
	//
	// GET /collections/{collectionUid}/generations/{elementType}
	GetGeneratedCollectionSpecs(ctx context.Context, params GetGeneratedCollectionSpecsParams) (GetGeneratedCollectionSpecsRes, error)
	// GetGroup implements getGroup operation.
	//
	// Gets information about a Postman [user group].
	//
	// [user group]: https://learning.postman.com/docs/collaborating-in-postman/user-groups/
	//
	// GET /groups/{groupId}
	GetGroup(ctx context.Context, params GetGroupParams) (GetGroupRes, error)
	// GetGroups implements getGroups operation.
	//
	// Gets all of a team's Postman [groups].
	//
	// [groups]: https://learning.postman.com/docs/collaborating-in-postman/user-groups/
	//
	// GET /groups
	GetGroups(ctx context.Context) (GetGroupsRes, error)
	// GetMock implements getMock operation.
	//
	// Gets information about a mock server.
	//
	// GET /mocks/{mockId}
	GetMock(ctx context.Context, params GetMockParams) (GetMockRes, error)
	// GetMockCallLogs implements getMockCallLogs operation.
	//
	// Gets a mock server's call logs. You can get a maximum of 6.5MB of call logs or a total of 100 call
	// logs, whichever limit is met first in one API call.
	//
	// GET /mocks/{mockId}/call-logs
	GetMockCallLogs(ctx context.Context, params GetMockCallLogsParams) (GetMockCallLogsRes, error)
	// GetMockServerResponse implements getMockServerResponse operation.
	//
	// Gets information about a server response.
	//
	// GET /mocks/{mockId}/server-responses/{serverResponseId}
	GetMockServerResponse(ctx context.Context, params GetMockServerResponseParams) (GetMockServerResponseRes, error)
	// GetMockServerResponses implements getMockServerResponses operation.
	//
	// Gets all of a mock server's server responses.
	//
	// GET /mocks/{mockId}/server-responses
	GetMockServerResponses(ctx context.Context, params GetMockServerResponsesParams) (GetMockServerResponsesRes, error)
	// GetMocks implements getMocks operation.
	//
	// Gets all active mock servers. By default, this endpoint returns only mock servers you created across
	// all workspaces.
	//
	// GET /mocks
	GetMocks(ctx context.Context, params GetMocksParams) (GetMocksRes, error)
	// GetMonitor implements getMonitor operation.
	//
	// Gets information about a monitor.
	//
	// GET /monitors/{monitorId}
	GetMonitor(ctx context.Context, params GetMonitorParams) (GetMonitorRes, error)
	// GetMonitors implements getMonitors operation.
	//
	// Gets all monitors.
	//
	// GET /monitors
	GetMonitors(ctx context.Context, params GetMonitorsParams) (GetMonitorsRes, error)
	// GetPullRequest implements getPullRequest operation.
	//
	// Gets information about a pull request, such as the source and destination details, who reviewed the
	// pull request, the merge's current status, and whether the element is accessible.
	//
	// GET /pull-requests/{pullRequestId}
	GetPullRequest(ctx context.Context, params GetPullRequestParams) (GetPullRequestRes, error)
	// GetRequestComments implements getRequestComments operation.
	//
	// Gets all comments left by users in a request.
	//
	// GET /collections/{collectionId}/requests/{requestId}/comments
	GetRequestComments(ctx context.Context, params GetRequestCommentsParams) (GetRequestCommentsRes, error)
	// GetResponseComments implements getResponseComments operation.
	//
	// Gets all comments left by users in a response.
	//
	// GET /collections/{collectionId}/responses/{responseId}/comments
	GetResponseComments(ctx context.Context, params GetResponseCommentsParams) (GetResponseCommentsRes, error)
	// GetRunnerInstances implements getRunnerInstances operation.
	//
	// Gets all instances of the runner polling Postman for upcoming monitor runs. Instances are runner
	// executions that share the same runner ID and key.
	//
	// GET /runners/{runnerId}/instances
	GetRunnerInstances(ctx context.Context, params GetRunnerInstancesParams) (GetRunnerInstancesRes, error)
	// GetRunnerMetrics implements getRunnerMetrics operation.
	//
	// Gets the Postman server-side metrics for a runner instance. Metrics include information such as
	// monitor run queues and last polling date.
	//
	// GET /runners/{runnerId}/metrics
	GetRunnerMetrics(ctx context.Context, params GetRunnerMetricsParams) (GetRunnerMetricsRes, error)
	// GetSdk implements getSdk operation.
	//
	// Returns information about the SDK, including the current build job status.
	//
	// GET /sdks/{sdkId}
	GetSdk(ctx context.Context, params GetSdkParams) (GetSdkRes, error)
	// GetSdkDownloadUrl implements getSdkDownloadUrl operation.
	//
	// Gets a short-lived signed URL for the generated SDK archive (zip). The generated URL is created on
	// demand and expires within a few minutes.
	//
	// GET /sdks/{sdkId}/downloads
	GetSdkDownloadUrl(ctx context.Context, params GetSdkDownloadUrlParams) (GetSdkDownloadUrlRes, error)
	// GetSdkGitConnection implements getSdkGitConnection operation.
	//
	// Gets information about an SDK's Git connection. The response includes the SDK currently sent to the
	// targetBranch and the most recent SDK-update pull request.
	//
	// GET /sdk-git-connections/{sdkGitConnectionId}
	GetSdkGitConnection(ctx context.Context, params GetSdkGitConnectionParams) (GetSdkGitConnectionRes, error)
	// GetSdkGitConnectionPullRequests implements getSdkGitConnectionPullRequests operation.
	//
	// Lists all SDK update pull requests for the Git connection, in order of newest first by its
	// `updatedAt` property.
	//
	// GET /sdk-git-connections/{sdkGitConnectionId}/pull-requests
	GetSdkGitConnectionPullRequests(ctx context.Context, params GetSdkGitConnectionPullRequestsParams) (GetSdkGitConnectionPullRequestsRes, error)
	// GetSdkGitConnections implements getSdkGitConnections operation.
	//
	// Gets all Git repository connections the authenticated user has access to in the given workspace.
	// Each connection links one Postman Collection or specification and one SDK language to a target Git
	// repository.
	//
	// GET /sdk-git-connections
	GetSdkGitConnections(ctx context.Context, params GetSdkGitConnectionsParams) (GetSdkGitConnectionsRes, error)
	// GetSdks implements getSdks operation.
	//
	// Lists all SDKs the authenticated user has access to.
	//
	// GET /sdks
	GetSdks(ctx context.Context, params GetSdksParams) (GetSdksRes, error)
	// GetSecretTypes implements getSecretTypes operation.
	//
	// Gets the metadata of the secret types supported by Postman's [Secret Scanner]. You can use a secret
	// type's ID in the response to query data with the POST `/detected-secrets/{secretId}` endpoint.
	//
	// [Secret Scanner]: https://learning.postman.com/docs/administration/secret-scanner/
	//
	// GET /secret-types
	GetSecretTypes(ctx context.Context) (GetSecretTypesRes, error)
	// GetSourceCollectionStatus implements getSourceCollectionStatus operation.
	//
	// Checks whether there is a change between the forked collection and its parent (source) collection.
	//
	// GET /collections/{collectionId}/source-status
	GetSourceCollectionStatus(ctx context.Context, params GetSourceCollectionStatusParams) (GetSourceCollectionStatusRes, error)
	// GetSpec implements getSpec operation.
	//
	// Gets information about an API specification.
	//
	// GET /specs/{specId}
	GetSpec(ctx context.Context, params GetSpecParams) (GetSpecRes, error)
	// GetSpecCollections implements getSpecCollections operation.
	//
	// Gets all of an API specification's generated collections.
	//
	// GET /specs/{specId}/generations/{elementType}
	GetSpecCollections(ctx context.Context, params GetSpecCollectionsParams) (GetSpecCollectionsRes, error)
	// GetSpecDefinition implements getSpecDefinition operation.
	//
	// Gets the complete contents of an OpenAPI or AsyncAPI specification's definition.
	//
	// GET /specs/{specId}/definitions
	GetSpecDefinition(ctx context.Context, params GetSpecDefinitionParams) (GetSpecDefinitionRes, error)
	// GetSpecFile implements getSpecFile operation.
	//
	// Gets the contents of an API specification's file.
	//
	// GET /specs/{specId}/files/{filePath}
	GetSpecFile(ctx context.Context, params GetSpecFileParams) (GetSpecFileRes, error)
	// GetSpecFiles implements getSpecFiles operation.
	//
	// Gets all the files in an API specification.
	//
	// GET /specs/{specId}/files
	GetSpecFiles(ctx context.Context, params GetSpecFilesParams) (GetSpecFilesRes, error)
	// GetSpecVersionTag implements getSpecVersionTag operation.
	//
	// Gets information about a specification's version tag. The response returns a snapshot of a
	// specification at a point in time that lets you track changes to your specifications over time.
	//
	// GET /specs/{specId}/version-tags/{tagId}/files
	GetSpecVersionTag(ctx context.Context, params GetSpecVersionTagParams) (GetSpecVersionTagRes, error)
	// GetSpecVersionTags implements getSpecVersionTags operation.
	//
	// Gets a list of a specification's version tags.
	//
	// GET /specs/{specId}/version-tags
	GetSpecVersionTags(ctx context.Context, params GetSpecVersionTagsParams) (GetSpecVersionTagsRes, error)
	// GetTaggedEntities implements getTaggedEntities operation.
	//
	// Gets Postman elements (entities) by a given tag. Tags enable you to organize and search
	// [workspaces], [APIs], and [collections] that contain shared tags.
	//
	// [workspaces]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#tagging-a-workspace
	// [APIs]: https://learning.postman.com/docs/designing-and-developing-your-api/managing-apis/#tagging-apis
	// [collections]: https://learning.postman.com/docs/collections/using-collections/#tagging-a-collection
	//
	// GET /tags/{slug}/entities
	GetTaggedEntities(ctx context.Context, params GetTaggedEntitiesParams) (GetTaggedEntitiesRes, error)
	// GetTeam implements getTeam operation.
	//
	// Gets information about a Postman team.
	//
	// GET /teams/{teamId}
	GetTeam(ctx context.Context, params GetTeamParams) (GetTeamRes, error)
	// GetTeamAccessRequests implements getTeamAccessRequests operation.
	//
	// Gets a team's pending access requests.
	//
	// GET /teams/{teamId}/access-requests
	GetTeamAccessRequests(ctx context.Context, params GetTeamAccessRequestsParams) (GetTeamAccessRequestsRes, error)
	// GetTeamSettings implements getTeamSettings operation.
	//
	// Gets a team's settings.
	//
	// GET /teams/{teamId}/settings
	GetTeamSettings(ctx context.Context, params GetTeamSettingsParams) (GetTeamSettingsRes, error)
	// GetTeamUser implements getTeamUser operation.
	//
	// Gets information about a user on the Postman team.
	//
	// GET /users/{userId}
	GetTeamUser(ctx context.Context, params GetTeamUserParams) (GetTeamUserRes, error)
	// GetTeamUsers implements getTeamUsers operation.
	//
	// Gets information about all users on the [Postman team].
	//
	// [Postman team]: https://learning.postman.com/docs/collaborating-in-postman/working-with-your-team/collaboration-overview/
	//
	// GET /users
	GetTeamUsers(ctx context.Context, params GetTeamUsersParams) (GetTeamUsersRes, error)
	// GetTeams implements getTeams operation.
	//
	// Gets all Postman teams in your organization.
	//
	// GET /teams
	GetTeams(ctx context.Context, params GetTeamsParams) (GetTeamsRes, error)
	// GetWorkspace implements getWorkspace operation.
	//
	// Gets information about a workspace.
	//
	// GET /workspaces/{workspaceId}
	GetWorkspace(ctx context.Context, params GetWorkspaceParams) (GetWorkspaceRes, error)
	// GetWorkspaceActivityFeed implements getWorkspaceActivityFeed operation.
	//
	// Gets a workspace's [activity feed]. Activity feeds return information about who added or removed
	// collections, environments, or elements from a workspace, and users that join or leave a workspace.
	//
	// [activity feed]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/changelog-and-restoring-collections/#view-workspace-activity
	//
	// GET /workspaces/{workspaceId}/activities
	GetWorkspaceActivityFeed(ctx context.Context, params GetWorkspaceActivityFeedParams) (GetWorkspaceActivityFeedRes, error)
	// GetWorkspaceGlobalVariables implements getWorkspaceGlobalVariables operation.
	//
	// Gets a workspace's global [variables]. Global variables enable you to access data between
	// collections, requests, scripts, and environments and are available throughout a workspace.
	//
	// [variables]: https://learning.postman.com/docs/sending-requests/variables/#variable-scopes
	//
	// GET /workspaces/{workspaceId}/global-variables
	GetWorkspaceGlobalVariables(ctx context.Context, params GetWorkspaceGlobalVariablesParams) (GetWorkspaceGlobalVariablesRes, error)
	// GetWorkspaceRoles implements getWorkspaceRoles operation.
	//
	// Gets the roles of users, user groups, and partners in a workspace.
	//
	// GET /workspaces/{workspaceId}/roles
	GetWorkspaceRoles(ctx context.Context, params GetWorkspaceRolesParams) (GetWorkspaceRolesRes, error)
	// GetWorkspaceTags implements getWorkspaceTags operation.
	//
	// Gets all the tags associated with a workspace.
	//
	// GET /workspaces/{workspaceId}/tags
	GetWorkspaceTags(ctx context.Context, params GetWorkspaceTagsParams) (GetWorkspaceTagsRes, error)
	// GetWorkspaceUpdate implements getWorkspaceUpdate operation.
	//
	// Gets information about a workspace update.
	//
	// GET /workspaces/{workspaceId}/updates/{updateId}
	GetWorkspaceUpdate(ctx context.Context, params GetWorkspaceUpdateParams) (GetWorkspaceUpdateRes, error)
	// GetWorkspaceUpdates implements getWorkspaceUpdates operation.
	//
	// Gets a list of workspace updates for the given workspace.
	//
	// GET /workspaces/{workspaceId}/updates
	GetWorkspaceUpdates(ctx context.Context, params GetWorkspaceUpdatesParams) (GetWorkspaceUpdatesRes, error)
	// GetWorkspaces implements getWorkspaces operation.
	//
	// Gets all [workspaces]. The response includes your workspaces and any workspaces that you have access
	// to.
	//
	// [workspaces]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/
	//
	// GET /workspaces
	GetWorkspaces(ctx context.Context, params GetWorkspacesParams) (GetWorkspacesRes, error)
	// ImportOpenApiDefinition implements importOpenApiDefinition operation.
	//
	// Imports an OpenAPI definition into Postman as a new [Postman Collection].
	//
	// [Postman Collection]: https://learning.postman.com/docs/getting-started/creating-the-first-collection/
	//
	// POST /import/openapi
	ImportOpenApiDefinition(ctx context.Context, req ImportOpenApiDefinition, params ImportOpenApiDefinitionParams) (ImportOpenApiDefinitionRes, error)
	// ListPrivateNetworkAddRequests implements listPrivateNetworkAddRequests operation.
	//
	// Gets all requests to add workspaces to your team's [Private API Network].
	//
	// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
	//
	// GET /network/private/network-entity/request/all
	ListPrivateNetworkAddRequests(ctx context.Context, params ListPrivateNetworkAddRequestsParams) (ListPrivateNetworkAddRequestsRes, error)
	// ListPrivateNetworkWorkspaces implements listPrivateNetworkWorkspaces operation.
	//
	// Gets information workspaces added to your team's [Private API Network].
	//
	// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
	//
	// GET /network/private
	ListPrivateNetworkWorkspaces(ctx context.Context, params ListPrivateNetworkWorkspacesParams) (ListPrivateNetworkWorkspacesRes, error)
	// ManagePartnerWorkspaceInvites implements managePartnerWorkspaceInvites operation.
	//
	// Manages invitations and access to your team's [Partner Workspaces]. You can use this endpoint to:.
	//
	// [Partner Workspaces]: https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/partner-workspaces/manage/
	//
	// POST /invitations
	ManagePartnerWorkspaceInvites(ctx context.Context, req ManagePartnerWorkspaceInvites) (ManagePartnerWorkspaceInvitesRes, error)
	// ManageTeamMemberRoles implements manageTeamMemberRoles operation.
	//
	// Adds or removes member roles in groups, teams, organizations, as well as individual users' roles.
	//
	// POST /teams/{teamId}/bulk-members
	ManageTeamMemberRoles(ctx context.Context, req *ManageTeamMemberRoles, params ManageTeamMemberRolesParams) (ManageTeamMemberRolesRes, error)
	// MergeCollectionFork implements mergeCollectionFork operation.
	//
	// This endpoint is deprecated.
	//
	// POST /collections/merge
	MergeCollectionFork(ctx context.Context, req *MergeCollectionFork) (MergeCollectionForkRes, error)
	// MergeEnvironmentFork implements mergeEnvironmentFork operation.
	//
	// [Merges] a forked environment back into its parent environment.
	//
	// [Merges]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/#merge-changes-from-a-fork
	//
	// POST /environments/{environmentId}/merges
	MergeEnvironmentFork(ctx context.Context, req *MergeEnvironmentFork, params MergeEnvironmentForkParams) (MergeEnvironmentForkRes, error)
	// PatchCollection implements patchCollection operation.
	//
	// Updates specific collection information, such as its name, events, or its variables. For more
	// information, see the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// PATCH /collections/{collectionId}
	PatchCollection(ctx context.Context, req *UpdateCollection, params PatchCollectionParams) (PatchCollectionRes, error)
	// PatchEnvironment implements patchEnvironment operation.
	//
	// Updates specific environment properties, such as its name and variables.
	//
	// PATCH /environments/{environmentId}
	PatchEnvironment(ctx context.Context, req PatchEnvironment, params PatchEnvironmentParams) (PatchEnvironmentRes, error)
	// PatchWorkspaceUpdate implements patchWorkspaceUpdate operation.
	//
	// Updates a workspace update.
	//
	// PATCH /workspaces/{workspaceId}/updates/{updateId}
	PatchWorkspaceUpdate(ctx context.Context, req *UpdateWorkspaceUpdate, params PatchWorkspaceUpdateParams) (PatchWorkspaceUpdateRes, error)
	// PublishDocumentation implements publishDocumentation operation.
	//
	// Publishes a collection's documentation. This makes it publicly available to anyone with the link to
	// the documentation.
	//
	// PUT /collections/{collectionId}/public-documentations
	PublishDocumentation(ctx context.Context, req *PublishDocumentation, params PublishDocumentationParams) (PublishDocumentationRes, error)
	// PublishMock implements publishMock operation.
	//
	// Publishes a mock server. Publishing a mock server sets its Access Control configuration setting to
	// public.
	//
	// POST /mocks/{mockId}/publish
	PublishMock(ctx context.Context, params PublishMockParams) (PublishMockRes, error)
	// PullCollectionChanges implements pullCollectionChanges operation.
	//
	// Pulls the changes from a parent (source) collection into the forked collection. In the endpoint's
	// response:.
	//
	// PUT /collections/{collectionId}/pulls
	PullCollectionChanges(ctx context.Context, params PullCollectionChangesParams) (PullCollectionChangesRes, error)
	// PullEnvironment implements pullEnvironment operation.
	//
	// [Pulls] the changes from a parent (source) environment into the forked environment.
	//
	// [Pulls]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/forking-elements/#pull-updates-from-a-parent-element
	//
	// POST /environments/{environmentUid}/pulls
	PullEnvironment(ctx context.Context, req *PullEnvironmentForkChanges, params PullEnvironmentParams) (PullEnvironmentRes, error)
	// PutCollection implements putCollection operation.
	//
	// Replaces the contents of a collection using the [Postman Collection v2.1.0 schema format]. Include
	// the collection's ID values in the request body. If you do not, the endpoint removes the existing
	// items and creates new items.
	//
	// [Postman Collection v2.1.0 schema format]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// PUT /collections/{collectionId}
	PutCollection(ctx context.Context, req *ReplaceCollectionData, params PutCollectionParams) (PutCollectionRes, error)
	// PutEnvironment implements putEnvironment operation.
	//
	// Replaces all the contents of an environment with the given information.
	//
	// PUT /environments/{environmentId}
	PutEnvironment(ctx context.Context, req *ReplaceEnvironmentData, params PutEnvironmentParams) (PutEnvironmentRes, error)
	// RemoveTeamMembers implements removeTeamMembers operation.
	//
	// Removes entities, such as users or organizations, from your Postman team. On success, this returns
	// an HTTP `204 No Content` response.
	//
	// DELETE /teams/{teamId}/bulk-members
	RemoveTeamMembers(ctx context.Context, req *RemoveTeamMembers, params RemoveTeamMembersParams) (RemoveTeamMembersRes, error)
	// RemoveWorkspaceFromPrivateNetwork implements removeWorkspaceFromPrivateNetwork operation.
	//
	// Removes a workspace from your team's [Private API Network].
	//
	// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
	//
	// DELETE /network/private/workspace/{workspaceId}
	RemoveWorkspaceFromPrivateNetwork(ctx context.Context, params RemoveWorkspaceFromPrivateNetworkParams) (RemoveWorkspaceFromPrivateNetworkRes, error)
	// ResolveCommentThread implements resolveCommentThread operation.
	//
	// Resolves a comment and any associated replies. On success, this returns an HTTP `204 No Content`
	// response.
	//
	// POST /comments-resolutions/{threadId}
	ResolveCommentThread(ctx context.Context, params ResolveCommentThreadParams) (ResolveCommentThreadRes, error)
	// RespondPrivateNetworkAddRequest implements respondPrivateNetworkAddRequest operation.
	//
	// Responds to a user's request to add a workspace to your team's [Private API Network]. Only managers
	// can approve or deny a request. Once approved, the workspace will appear in the team's Private API
	// Network.
	//
	// [Private API Network]: https://learning.postman.com/docs/collaborating-in-postman/adding-private-network/
	//
	// PUT /network/private/network-entity/request/{requestId}
	RespondPrivateNetworkAddRequest(ctx context.Context, req *RespondPanElementAddRequestBody, params RespondPrivateNetworkAddRequestParams) (RespondPrivateNetworkAddRequestRes, error)
	// ReviewPullRequest implements reviewPullRequest operation.
	//
	// Updates the [review] status of a pull request.
	//
	// [review]: https://learning.postman.com/docs/collaborating-in-postman/using-version-control/reviewing-pull-requests/
	//
	// POST /pull-requests/{pullRequestId}/tasks
	ReviewPullRequest(ctx context.Context, req *ReviewPullRequest, params ReviewPullRequestParams) (ReviewPullRequestRes, error)
	// RevokeOauthToken implements revokeOauthToken operation.
	//
	// Revokes an active OAuth 2.0 access token and prevents further use of it for authentication. Once
	// revoked, the token can't be used for any API requests.
	//
	// POST /oauth2/token/revoke
	RevokeOauthToken(ctx context.Context, req *RevokeOauthToken) (RevokeOauthTokenRes, error)
	// RunMonitor implements runMonitor operation.
	//
	// Runs a monitor and returns its run results.
	//
	// POST /monitors/{monitorId}/run
	RunMonitor(ctx context.Context, params RunMonitorParams) (RunMonitorRes, error)
	// SchemaSecurityValidation implements schemaSecurityValidation operation.
	//
	// Performs an analysis on the given definition and returns any issues based on your
	// [predefined rulesets]. This endpoint can help you understand the violations' impact and offers
	// solutions to help you resolve any errors. You can include this endpoint to your CI/CD process to
	// automate schema validation.
	//
	// [predefined rulesets]: https://learning.postman.com/docs/api-governance/configurable-rules/configurable-rules-overview/
	//
	// POST /security/api-validation
	SchemaSecurityValidation(ctx context.Context, req *SchemaValidationRequestBody) (SchemaSecurityValidationRes, error)
	// SearchPostmanResources implements searchPostmanResources operation.
	//
	// Searches Postman for resources such as workspaces, collections, requests, and other resource types.
	// You can filter results by ownership, visibility, tags, and other criteria.
	//
	// POST /search
	SearchPostmanResources(ctx context.Context, req *SearchPostmanResources, params SearchPostmanResourcesParams) (SearchPostmanResourcesRes, error)
	// SyncCollectionWithSpec implements syncCollectionWithSpec operation.
	//
	// Syncs a collection generated from an API specification. This is an asynchronous endpoint that
	// returns an HTTP `202 Accepted` response.
	//
	// PUT /collections/{collectionUid}/synchronizations
	SyncCollectionWithSpec(ctx context.Context, params SyncCollectionWithSpecParams) (SyncCollectionWithSpecRes, error)
	// SyncSpecWithCollection implements syncSpecWithCollection operation.
	//
	// Syncs an API specification linked to a collection. This is an asynchronous endpoint that returns an
	// HTTP `202 Accepted` response.
	//
	// PUT /specs/{specId}/synchronizations
	SyncSpecWithCollection(ctx context.Context, params SyncSpecWithCollectionParams) (SyncSpecWithCollectionRes, error)
	// TransferCollectionFolders implements transferCollectionFolders operation.
	//
	// Copies or moves folders into a collection or folder.
	//
	// POST /collection-folders-transfers
	TransferCollectionFolders(ctx context.Context, req *TransferCollectionItems) (TransferCollectionFoldersRes, error)
	// TransferCollectionRequests implements transferCollectionRequests operation.
	//
	// Copies or moves requests into a collection or folder.
	//
	// POST /collection-requests-transfers
	TransferCollectionRequests(ctx context.Context, req *TransferCollectionItems) (TransferCollectionRequestsRes, error)
	// TransferCollectionResponses implements transferCollectionResponses operation.
	//
	// Copies or moves responses into a request.
	//
	// POST /collection-responses-transfers
	TransferCollectionResponses(ctx context.Context, req *TransferCollectionItems) (TransferCollectionResponsesRes, error)
	// TransferWorkspaceElement implements transferWorkspaceElement operation.
	//
	// Transfers a [Postman element] from one workspace to another workspace. Supported elements include
	// collections, environments, mocks, monitors, and Flows modules and actions.
	//
	// [Postman element]: https://learning.postman.com/docs/getting-started/basics/postman-elements/
	//
	// POST /workspaces/{workspaceId}/element-transfers
	TransferWorkspaceElement(ctx context.Context, req *TransferWorkspaceElement, params TransferWorkspaceElementParams) (TransferWorkspaceElementRes, error)
	// TransferWorkspaceToTeam implements transferWorkspaceToTeam operation.
	//
	// Transfers a workspace from one team (`source`) to another team (`destination`).
	//
	// PATCH /workspaces/{workspaceId}/transfers
	TransferWorkspaceToTeam(ctx context.Context, req *TransferWorkspaceToTeam, params TransferWorkspaceToTeamParams) (TransferWorkspaceToTeamRes, error)
	// TransformCollectionToOpenApi implements transformCollectionToOpenApi operation.
	//
	// Transforms an existing Postman Collection into a stringified OpenAPI definition.
	//
	// GET /collections/{collectionId}/transformations
	TransformCollectionToOpenApi(ctx context.Context, params TransformCollectionToOpenApiParams) (TransformCollectionToOpenApiRes, error)
	// UnpublishDocumentation implements unpublishDocumentation operation.
	//
	// Unpublishes a collection's documentation. On success, this returns an HTTP `204 No Content`
	// response.
	//
	// DELETE /collections/{collectionId}/public-documentations
	UnpublishDocumentation(ctx context.Context, params UnpublishDocumentationParams) (UnpublishDocumentationRes, error)
	// UnpublishMock implements unpublishMock operation.
	//
	// Unpublishes a mock server. Unpublishing a mock server sets its Access Control configuration setting
	// to private.
	//
	// DELETE /mocks/{mockId}/unpublish
	UnpublishMock(ctx context.Context, params UnpublishMockParams) (UnpublishMockRes, error)
	// UpdateCollectionComment implements updateCollectionComment operation.
	//
	// Updates a comment on a collection.
	//
	// PUT /collections/{collectionId}/comments/{commentId}
	UpdateCollectionComment(ctx context.Context, req *CommentUpdate, params UpdateCollectionCommentParams) (UpdateCollectionCommentRes, error)
	// UpdateCollectionFolder implements updateCollectionFolder operation.
	//
	// Updates a folder in a collection. For a complete list of properties, refer to the Folder entry in
	// the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// PUT /collections/{collectionId}/folders/{folderId}
	UpdateCollectionFolder(ctx context.Context, req *UpdateFolder, params UpdateCollectionFolderParams) (UpdateCollectionFolderRes, error)
	// UpdateCollectionRequest implements updateCollectionRequest operation.
	//
	// Updates a request in a collection. For a complete list of properties, refer to the Request entry in
	// the [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// PUT /collections/{collectionId}/requests/{requestId}
	UpdateCollectionRequest(ctx context.Context, req *UpdateRequest, params UpdateCollectionRequestParams) (UpdateCollectionRequestRes, error)
	// UpdateCollectionResponse implements updateCollectionResponse operation.
	//
	// Updates a response in a collection. For a complete list of properties, see the
	// [Postman Collection Format documentation].
	//
	// [Postman Collection Format documentation]: https://schema.postman.com/collection/json/v2.1.0/draft-07/docs/index.html
	//
	// PUT /collections/{collectionId}/responses/{responseId}
	UpdateCollectionResponse(ctx context.Context, req *UpdateCollectionResponse1, params UpdateCollectionResponseParams) (UpdateCollectionResponseRes, error)
	// UpdateCollectionRoles implements updateCollectionRoles operation.
	//
	// Updates the roles of users, groups, or teams in a collection. On success, this returns an HTTP
	// `204 No Content` response.
	//
	// PATCH /collections/{collectionId}/roles
	UpdateCollectionRoles(ctx context.Context, req *UpdateCollectionRoles, params UpdateCollectionRolesParams) (UpdateCollectionRolesRes, error)
	// UpdateCollectionTags implements updateCollectionTags operation.
	//
	// Updates a collection's associated tags. This endpoint replaces all existing tags with those you pass
	// in the request body.
	//
	// PUT /collections/{collectionId}/tags
	UpdateCollectionTags(ctx context.Context, req *UpdateTags, params UpdateCollectionTagsParams) (UpdateCollectionTagsRes, error)
	// UpdateComponent implements updateComponent operation.
	//
	// Updates a component: - `name` — Rename the component. The new name must be unique within the team.
	// Archived components can't be renamed.
	//
	// PATCH /components/{componentId}
	UpdateComponent(ctx context.Context, req *UpdateComponentReq, params UpdateComponentParams) (UpdateComponentRes, error)
	// UpdateComponentDraft implements updateComponentDraft operation.
	//
	// Updates a component's draft. Component drafts contain unpublished edits to a component, which may be
	// different from a recently published version.
	//
	// PATCH /components/{componentId}/drafts
	UpdateComponentDraft(ctx context.Context, req *UpdateComponentDraft, params UpdateComponentDraftParams) (UpdateComponentDraftRes, error)
	// UpdateDetectedSecretResolutions implements updateDetectedSecretResolutions operation.
	//
	// Updates the resolution status of a secret detected in a workspace.
	//
	// PUT /detected-secrets/{secretId}
	UpdateDetectedSecretResolutions(ctx context.Context, req *UpdateSecretResolutionRequest, params UpdateDetectedSecretResolutionsParams) (UpdateDetectedSecretResolutionsRes, error)
	// UpdateFolderComment implements updateFolderComment operation.
	//
	// Updates a comment on a folder.
	//
	// PUT /collections/{collectionId}/folders/{folderId}/comments/{commentId}
	UpdateFolderComment(ctx context.Context, req *CommentUpdate, params UpdateFolderCommentParams) (UpdateFolderCommentRes, error)
	// UpdateMock implements updateMock operation.
	//
	// Updates a mock server's properties, such as its name or collection.
	//
	// PUT /mocks/{mockId}
	UpdateMock(ctx context.Context, req *UpdateMock, params UpdateMockParams) (UpdateMockRes, error)
	// UpdateMockServerResponse implements updateMockServerResponse operation.
	//
	// Updates a server response.
	//
	// PUT /mocks/{mockId}/server-responses/{serverResponseId}
	UpdateMockServerResponse(ctx context.Context, req *UpdateMockServerResponse, params UpdateMockServerResponseParams) (UpdateMockServerResponseRes, error)
	// UpdateMonitor implements updateMonitor operation.
	//
	// Updates a monitor's [configurations].
	//
	// [configurations]: https://learning.postman.com/docs/monitoring-your-api/setting-up-monitor/#configure-a-monitor
	//
	// PUT /monitors/{monitorId}
	UpdateMonitor(ctx context.Context, req *UpdateMonitor, params UpdateMonitorParams) (UpdateMonitorRes, error)
	// UpdatePanElementOrFolder implements updatePanElementOrFolder operation.
	//
	// This endpoint is deprecated.
	//
	// PUT /network/private/workspace/{workspaceId}
	UpdatePanElementOrFolder(ctx context.Context, req *UpdatePanElementOrFolderRequest, params UpdatePanElementOrFolderParams) (UpdatePanElementOrFolderRes, error)
	// UpdatePullRequest implements updatePullRequest operation.
	//
	// Updates an open pull request.
	//
	// PUT /pull-requests/{pullRequestId}
	UpdatePullRequest(ctx context.Context, req *UpdatePullRequest, params UpdatePullRequestParams) (UpdatePullRequestRes, error)
	// UpdateRequestComment implements updateRequestComment operation.
	//
	// Updates a comment on a request.
	//
	// PUT /collections/{collectionId}/requests/{requestId}/comments/{commentId}
	UpdateRequestComment(ctx context.Context, req *CommentUpdate, params UpdateRequestCommentParams) (UpdateRequestCommentRes, error)
	// UpdateResponseComment implements updateResponseComment operation.
	//
	// Updates a comment on a response.
	//
	// PUT /collections/{collectionId}/responses/{responseId}/comments/{commentId}
	UpdateResponseComment(ctx context.Context, req *CommentUpdate, params UpdateResponseCommentParams) (UpdateResponseCommentRes, error)
	// UpdateSdkGitConnection implements updateSdkGitConnection operation.
	//
	// Updates the Git connection's lifecycle status:.
	//
	// PUT /sdk-git-connections/{sdkGitConnectionId}
	UpdateSdkGitConnection(ctx context.Context, req *UpdateSdkGitConnection, params UpdateSdkGitConnectionParams) (UpdateSdkGitConnectionRes, error)
	// UpdateSpecFile implements updateSpecFile operation.
	//
	// Updates a file for an OpenAPI or protobuf 2 or 3 specification.
	//
	// PATCH /specs/{specId}/files/{filePath}
	UpdateSpecFile(ctx context.Context, req *UpdateSpecFile, params UpdateSpecFileParams) (UpdateSpecFileRes, error)
	// UpdateSpecProperties implements updateSpecProperties operation.
	//
	// Updates an API specification's properties, such as its name.
	//
	// PATCH /specs/{specId}
	UpdateSpecProperties(ctx context.Context, req *UpdateSpecProperties, params UpdateSpecPropertiesParams) (UpdateSpecPropertiesRes, error)
	// UpdateSpecSyncOptions implements updateSpecSyncOptions operation.
	//
	// Updates the [sync options] for a specification's generated collection.
	//
	// [sync options]: https://learning.postman.com/docs/design-apis/specifications/generate-collections/#configure-sync-settings
	//
	// PATCH /specs/{specId}/collections/{collectionId}/sync-options
	UpdateSpecSyncOptions(ctx context.Context, req *ApiSpecSyncOptions, params UpdateSpecSyncOptionsParams) (UpdateSpecSyncOptionsRes, error)
	// UpdateTeamSettings implements updateTeamSettings operation.
	//
	// Updates a team's settings.
	//
	// PUT /teams/{teamId}/settings
	UpdateTeamSettings(ctx context.Context, req *UpdateTeamSettings, params UpdateTeamSettingsParams) (UpdateTeamSettingsRes, error)
	// UpdateWorkspace implements updateWorkspace operation.
	//
	// Updates a workspace's property, such as its name or visibility.
	//
	// PUT /workspaces/{workspaceId}
	UpdateWorkspace(ctx context.Context, req *UpdateWorkspaceRequest, params UpdateWorkspaceParams) (UpdateWorkspaceRes, error)
	// UpdateWorkspaceGlobalVariables implements updateWorkspaceGlobalVariables operation.
	//
	// Updates and replaces a workspace's global [variables]. This endpoint replaces all existing global
	// variables with the variables you pass in the request body.
	//
	// [variables]: https://learning.postman.com/docs/sending-requests/variables/#variable-scopes
	//
	// PUT /workspaces/{workspaceId}/global-variables
	UpdateWorkspaceGlobalVariables(ctx context.Context, req *UpdateGlobalVariables, params UpdateWorkspaceGlobalVariablesParams) (UpdateWorkspaceGlobalVariablesRes, error)
	// UpdateWorkspaceRoles implements updateWorkspaceRoles operation.
	//
	// Updates the roles of users, [user groups], or partners in a workspace. To get a list of roles, use
	// the GET `/workspace-roles` endpoint. To get a group ID, use the GET `/groups` endpoint.
	//
	// [user groups]: https://learning.postman.com/docs/collaborating-in-postman/user-groups/
	//
	// PATCH /workspaces/{workspaceId}/roles
	UpdateWorkspaceRoles(ctx context.Context, req *UpdateWorkspaceRoles, params UpdateWorkspaceRolesParams) (UpdateWorkspaceRolesRes, error)
	// UpdateWorkspaceTags implements updateWorkspaceTags operation.
	//
	// Updates a workspace's associated tags. This endpoint replaces all existing tags with those you pass
	// in the request body.
	//
	// PUT /workspaces/{workspaceId}/tags
	UpdateWorkspaceTags(ctx context.Context, req *UpdateTags, params UpdateWorkspaceTagsParams) (UpdateWorkspaceTagsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
