// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleApiKey handles apiKey security.
	// A Postman API key.
	HandleApiKey(ctx context.Context, operationName OperationName, t ApiKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesApiKey is a private map storing roles per operation.
var operationRolesApiKey = map[string][]string{
	AddWorkspaceToPrivateNetworkOperation:       []string{},
	ApproveDenyAccessRequestOperation:           []string{},
	AsyncMergePullCollectionForkOperation:       []string{},
	AsyncMergePullCollectionTaskStatusOperation: []string{},
	CreateAccessRequestOperation:                []string{},
	CreateCollectionOperation:                   []string{},
	CreateCollectionCommentOperation:            []string{},
	CreateCollectionFolderOperation:             []string{},
	CreateCollectionForkOperation:               []string{},
	CreateCollectionPullRequestOperation:        []string{},
	CreateCollectionRequestOperation:            []string{},
	CreateCollectionResponseOperation:           []string{},
	CreateComponentOperation:                    []string{},
	CreateComponentVersionOperation:             []string{},
	CreateEnvironmentOperation:                  []string{},
	CreateFolderCommentOperation:                []string{},
	CreateMockOperation:                         []string{},
	CreateMockServerResponseOperation:           []string{},
	CreateMonitorOperation:                      []string{},
	CreateRequestCommentOperation:               []string{},
	CreateResponseCommentOperation:              []string{},
	CreateSdkOperation:                          []string{},
	CreateSdkGitConnectionOperation:             []string{},
	CreateSpecOperation:                         []string{},
	CreateSpecFileOperation:                     []string{},
	CreateSpecVersionTagOperation:               []string{},
	CreateTeamOperation:                         []string{},
	CreateWebhookOperation:                      []string{},
	CreateWorkspaceOperation:                    []string{},
	CreateWorkspaceUpdateOperation:              []string{},
	DeleteCollectionOperation:                   []string{},
	DeleteCollectionAccessKeyOperation:          []string{},
	DeleteCollectionCommentOperation:            []string{},
	DeleteCollectionFolderOperation:             []string{},
	DeleteCollectionRequestOperation:            []string{},
	DeleteCollectionResponseOperation:           []string{},
	DeleteEnvironmentOperation:                  []string{},
	DeleteFolderCommentOperation:                []string{},
	DeleteMockOperation:                         []string{},
	DeleteMockServerResponseOperation:           []string{},
	DeleteMonitorOperation:                      []string{},
	DeleteRequestCommentOperation:               []string{},
	DeleteResponseCommentOperation:              []string{},
	DeleteSdkOperation:                          []string{},
	DeleteSpecOperation:                         []string{},
	DeleteSpecFileOperation:                     []string{},
	DeleteWorkspaceOperation:                    []string{},
	DeleteWorkspaceUpdateOperation:              []string{},
	DetectedSecretsQueriesOperation:             []string{},
	DuplicateCollectionOperation:                []string{},
	ForkEnvironmentOperation:                    []string{},
	GenerateCollectionOperation:                 []string{},
	GenerateOauthTokenOperation:                 []string{},
	GenerateServiceAccountTokenOperation:        []string{},
	GenerateSpecFromCollectionOperation:         []string{},
	GenerateToolOperation:                       []string{},
	GetAccountInvoicesOperation:                 []string{},
	GetAccountsOperation:                        []string{},
	GetAllComponentsOperation:                   []string{},
	GetAllSpecsOperation:                        []string{},
	GetAllWorkspaceRolesOperation:               []string{},
	GetAnalyticsDataOperation:                   []string{},
	GetAnalyticsMetadataOperation:               []string{},
	GetAsyncSpecTaskStatusOperation:             []string{},
	GetAuditLogEventActionsOperation:            []string{},
	GetAuditLogsOperation:                       []string{},
	GetAuthenticatedUserOperation:               []string{},
	GetCollectionOperation:                      []string{},
	GetCollectionAccessKeysOperation:            []string{},
	GetCollectionCommentsOperation:              []string{},
	GetCollectionFolderOperation:                []string{},
	GetCollectionForksOperation:                 []string{},
	GetCollectionPullRequestsOperation:          []string{},
	GetCollectionRequestOperation:               []string{},
	GetCollectionResponseOperation:              []string{},
	GetCollectionRolesOperation:                 []string{},
	GetCollectionTagsOperation:                  []string{},
	GetCollectionUpdatesTasksOperation:          []string{},
	GetCollectionsOperation:                     []string{},
	GetCollectionsForkedByUserOperation:         []string{},
	GetComponentOperation:                       []string{},
	GetComponentDraftOperation:                  []string{},
	GetComponentVersionOperation:                []string{},
	GetComponentVersionsOperation:               []string{},
	GetDetectedSecretsLocationsOperation:        []string{},
	GetDuplicateCollectionTaskStatusOperation:   []string{},
	GetEnvironmentOperation:                     []string{},
	GetEnvironmentForksOperation:                []string{},
	GetEnvironmentsOperation:                    []string{},
	GetFolderCommentsOperation:                  []string{},
	GetGeneratedCollectionSpecsOperation:        []string{},
	GetGroupOperation:                           []string{},
	GetGroupsOperation:                          []string{},
	GetMockOperation:                            []string{},
	GetMockCallLogsOperation:                    []string{},
	GetMockServerResponseOperation:              []string{},
	GetMockServerResponsesOperation:             []string{},
	GetMocksOperation:                           []string{},
	GetMonitorOperation:                         []string{},
	GetMonitorsOperation:                        []string{},
	GetPullRequestOperation:                     []string{},
	GetRequestCommentsOperation:                 []string{},
	GetResponseCommentsOperation:                []string{},
	GetRunnerInstancesOperation:                 []string{},
	GetRunnerMetricsOperation:                   []string{},
	GetSdkOperation:                             []string{},
	GetSdkDownloadUrlOperation:                  []string{},
	GetSdkGitConnectionOperation:                []string{},
	GetSdkGitConnectionPullRequestsOperation:    []string{},
	GetSdkGitConnectionsOperation:               []string{},
	GetSdksOperation:                            []string{},
	GetSecretTypesOperation:                     []string{},
	GetSourceCollectionStatusOperation:          []string{},
	GetSpecOperation:                            []string{},
	GetSpecCollectionsOperation:                 []string{},
	GetSpecDefinitionOperation:                  []string{},
	GetSpecFileOperation:                        []string{},
	GetSpecFilesOperation:                       []string{},
	GetSpecVersionTagOperation:                  []string{},
	GetSpecVersionTagsOperation:                 []string{},
	GetTaggedEntitiesOperation:                  []string{},
	GetTeamOperation:                            []string{},
	GetTeamAccessRequestsOperation:              []string{},
	GetTeamSettingsOperation:                    []string{},
	GetTeamUserOperation:                        []string{},
	GetTeamUsersOperation:                       []string{},
	GetTeamsOperation:                           []string{},
	GetWorkspaceOperation:                       []string{},
	GetWorkspaceActivityFeedOperation:           []string{},
	GetWorkspaceGlobalVariablesOperation:        []string{},
	GetWorkspaceRolesOperation:                  []string{},
	GetWorkspaceTagsOperation:                   []string{},
	GetWorkspaceUpdateOperation:                 []string{},
	GetWorkspaceUpdatesOperation:                []string{},
	GetWorkspacesOperation:                      []string{},
	ImportOpenApiDefinitionOperation:            []string{},
	ListPrivateNetworkAddRequestsOperation:      []string{},
	ListPrivateNetworkWorkspacesOperation:       []string{},
	ManagePartnerWorkspaceInvitesOperation:      []string{},
	ManageTeamMemberRolesOperation:              []string{},
	MergeCollectionForkOperation:                []string{},
	MergeEnvironmentForkOperation:               []string{},
	PatchCollectionOperation:                    []string{},
	PatchEnvironmentOperation:                   []string{},
	PatchWorkspaceUpdateOperation:               []string{},
	PublishDocumentationOperation:               []string{},
	PublishMockOperation:                        []string{},
	PullCollectionChangesOperation:              []string{},
	PullEnvironmentOperation:                    []string{},
	PutCollectionOperation:                      []string{},
	PutEnvironmentOperation:                     []string{},
	RemoveTeamMembersOperation:                  []string{},
	RemoveWorkspaceFromPrivateNetworkOperation:  []string{},
	ResolveCommentThreadOperation:               []string{},
	RespondPrivateNetworkAddRequestOperation:    []string{},
	ReviewPullRequestOperation:                  []string{},
	RevokeOauthTokenOperation:                   []string{},
	RunMonitorOperation:                         []string{},
	SchemaSecurityValidationOperation:           []string{},
	SearchPostmanResourcesOperation:             []string{},
	SyncCollectionWithSpecOperation:             []string{},
	SyncSpecWithCollectionOperation:             []string{},
	TransferCollectionFoldersOperation:          []string{},
	TransferCollectionRequestsOperation:         []string{},
	TransferCollectionResponsesOperation:        []string{},
	TransferWorkspaceElementOperation:           []string{},
	TransferWorkspaceToTeamOperation:            []string{},
	TransformCollectionToOpenApiOperation:       []string{},
	UnpublishDocumentationOperation:             []string{},
	UnpublishMockOperation:                      []string{},
	UpdateCollectionCommentOperation:            []string{},
	UpdateCollectionFolderOperation:             []string{},
	UpdateCollectionRequestOperation:            []string{},
	UpdateCollectionResponseOperation:           []string{},
	UpdateCollectionRolesOperation:              []string{},
	UpdateCollectionTagsOperation:               []string{},
	UpdateComponentOperation:                    []string{},
	UpdateComponentDraftOperation:               []string{},
	UpdateDetectedSecretResolutionsOperation:    []string{},
	UpdateFolderCommentOperation:                []string{},
	UpdateMockOperation:                         []string{},
	UpdateMockServerResponseOperation:           []string{},
	UpdateMonitorOperation:                      []string{},
	UpdatePanElementOrFolderOperation:           []string{},
	UpdatePullRequestOperation:                  []string{},
	UpdateRequestCommentOperation:               []string{},
	UpdateResponseCommentOperation:              []string{},
	UpdateSdkGitConnectionOperation:             []string{},
	UpdateSpecFileOperation:                     []string{},
	UpdateSpecPropertiesOperation:               []string{},
	UpdateSpecSyncOptionsOperation:              []string{},
	UpdateTeamSettingsOperation:                 []string{},
	UpdateWorkspaceOperation:                    []string{},
	UpdateWorkspaceGlobalVariablesOperation:     []string{},
	UpdateWorkspaceRolesOperation:               []string{},
	UpdateWorkspaceTagsOperation:                []string{},
}

// GetRolesForApiKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKey(operation string) []string {
	roles, ok := operationRolesApiKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityApiKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t ApiKey
	const parameterName = "X-API-Key"
	value := req.Header.Get(parameterName)
	if value == "" {
		return ctx, false, nil
	}
	t.APIKey = value
	t.Roles = operationRolesApiKey[operationName]
	rctx, err := s.sec.HandleApiKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKey provides apiKey security value.
	// A Postman API key.
	ApiKey(ctx context.Context, operationName OperationName) (ApiKey, error)
}

func (s *Client) securityApiKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKey\"")
	}
	req.Header.Set("X-API-Key", t.APIKey)
	return nil
}
